// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * UploadAssetInput is the typed input for upload_asset.
 */
export interface UploadAssetInput {
  /**
   * Filename is the original client-facing filename for the uploaded asset.
   */
  filename: string;
  /**
   * MIME is the asset media type, such as image/png.
   */
  mime: string;
  /**
   * DataBase64 is the raw asset content encoded as base64.
   */
  dataBase64: string;
  /**
   * Origin is the optional caller surface identifier.
   */
  origin?: string;
}
/**
 * UploadAssetOutput is the structured result for upload_asset.
 */
export interface UploadAssetOutput {
  /**
   * AssetID is the opaque stored asset URI.
   */
  assetId: string;
  /**
   * Filename is the stored filename metadata.
   */
  filename?: string;
  /**
   * MIME is the stored asset media type.
   */
  mime?: string;
  /**
   * Bytes is the stored asset size in bytes.
   */
  bytes: number /* int */;
}
/**
 * ListAssetsInput is the typed input for list_assets.
 */
export interface ListAssetsInput {
}
/**
 * AssetMetadata is the metadata summary for one stored asset.
 */
export interface AssetMetadata {
  /**
   * AssetID is the opaque stored asset URI.
   */
  assetId: string;
  /**
   * Filename is the original client-facing filename.
   */
  filename?: string;
  /**
   * MIME is the stored asset media type.
   */
  mime?: string;
  /**
   * Bytes is the stored asset size in bytes.
   */
  bytes: number /* int */;
}
/**
 * ListAssetsOutput is the structured result for list_assets.
 */
export interface ListAssetsOutput {
  /**
   * Assets is every stored asset metadata summary.
   */
  assets?: AssetMetadata[];
}
/**
 * GetAssetInput is the typed input for get_asset.
 */
export interface GetAssetInput {
  /**
   * AssetID addresses one stored asset by opaque asset URI.
   */
  assetId: string;
}
/**
 * GetAssetOutput is the structured result for get_asset.
 */
export interface GetAssetOutput {
  /**
   * AssetID is the opaque stored asset URI.
   */
  assetId: string;
  /**
   * Filename is the original client-facing filename.
   */
  filename?: string;
  /**
   * MIME is the stored asset media type.
   */
  mime?: string;
  /**
   * Bytes is the stored asset size in bytes.
   */
  bytes: number /* int */;
}
/**
 * DeleteAssetInput is the typed input for delete_asset.
 */
export interface DeleteAssetInput {
  /**
   * AssetID addresses one stored asset by opaque asset URI.
   */
  assetId: string;
}
/**
 * DeleteAssetOutput is the structured result for delete_asset.
 */
export interface DeleteAssetOutput {
  /**
   * AssetID is the deleted stored asset URI.
   */
  assetId: string;
  /**
   * Deleted reports whether the asset was removed.
   */
  deleted: boolean;
}
/**
 * EMUBox is a rectangle in EMU (English Metric Units; 914400 per inch) — the
 * coordinate space pptx-go lays out in. The canvas surface scales it to pixels.
 */
export interface EMUBox {
  x: number /* int64 */;
  y: number /* int64 */;
  w: number /* int64 */;
  h: number /* int64 */;
}
/**
 * NodePlacement is one node's resolved geometry on the slide canvas. Computed
 * server-side by mirroring pptx-go's deterministic box-stack layout, so the
 * editor canvas paints the SAME geometry the export uses (no second layout
 * authority re-coded in the browser). Path is the IR path to the node (for
 * click-to-select and the edit tools).
 */
export interface NodePlacement {
  /**
   * Path is the structural IR path to the node ([] = top level, e.g. [2] or [2,"left",0]).
   */
  path: IRPath;
  /**
   * Kind is the node kind discriminator.
   */
  kind: string;
  /**
   * Box is the node's resolved rectangle in EMU.
   */
  box: EMUBox;
}
/**
 * SlideLayout is the full canvas geometry for one slide: the canvas size plus
 * every node's placement, in deck (soul) coordinates.
 */
export interface SlideLayout {
  /**
   * CanvasWidth / CanvasHeight are the slide dimensions in EMU (16:9 by default).
   */
  canvasWidth: number /* int64 */;
  canvasHeight: number /* int64 */;
  /**
   * Placements are the per-node boxes in render order (containers before children).
   */
  placements?: NodePlacement[];
  /**
   * Overflow is true when the stacked content exceeds the body region (the one
   * irreducible divergence — surfaced honestly on-canvas).
   */
  overflow: boolean;
}
/**
 * SoulPalette is the deck soul's resolved colors + fonts, so the canvas paints
 * in the deck's actual visual language (matching the export) rather than the
 * app-chrome theme.
 */
export interface SoulPalette {
  canvas: string;
  surface: string;
  surfaceAlt: string;
  accent: string;
  accentText: string;
  textPrimary: string;
  textSecondary: string;
  textInverse: string;
  border: string;
  /**
   * HeadingFont / BodyFont / MonoFont are CSS font-family hints from the soul.
   */
  headingFont: string;
  bodyFont: string;
  monoFont: string;
}
/**
 * CommentTarget is the typed comment target address.
 */
export interface CommentTarget {
  /**
   * Kind identifies whether the comment points at a deck, slide, or node.
   */
  kind: string;
  /**
   * SlideID identifies the target slide when the comment is slide- or node-scoped.
   */
  slideId?: string;
  /**
   * IRPath is the optional structural path to a node target.
   */
  irPath?: any[];
}
/**
 * AddCommentInput is the typed input for add_comment.
 */
export interface AddCommentInput {
  /**
   * DeckID identifies the deck that owns the comment thread.
   */
  deckId: string;
  /**
   * Target identifies what the comment points at.
   */
  target: CommentTarget;
  /**
   * Body is the comment text.
   */
  body: string;
  /**
   * Kind is the optional comment classification such as note, todo, or question.
   */
  kind?: string;
  /**
   * Origin is the optional caller origin such as agent or app.
   */
  origin?: string;
}
/**
 * AddCommentOutput is the structured result for add_comment.
 */
export interface AddCommentOutput {
  /**
   * CommentID is the stored comment ID.
   */
  commentId: string;
}
/**
 * ListCommentsInput is the typed input for list_comments.
 */
export interface ListCommentsInput {
  /**
   * DeckID identifies which deck's comments to list.
   */
  deckId: string;
  /**
   * Resolved optionally filters comments by resolution state.
   */
  resolved?: boolean;
  /**
   * TargetKind optionally filters comments by target kind.
   */
  targetKind?: string;
}
/**
 * CommentView is the structured metadata for one stored comment.
 */
export interface CommentView {
  /**
   * CommentID is the stored comment ID.
   */
  commentId: string;
  /**
   * DeckID identifies the deck that owns the comment.
   */
  deckId: string;
  /**
   * Target identifies what the comment points at.
   */
  target: CommentTarget;
  /**
   * Body is the comment text.
   */
  body: string;
  /**
   * Kind is the comment classification.
   */
  kind?: string;
  /**
   * Origin is the caller origin such as agent or app.
   */
  origin?: string;
  /**
   * Resolved reports whether the comment has been resolved.
   */
  resolved: boolean;
  /**
   * CreatedAt is the comment creation time in UTC RFC3339 format.
   */
  createdAt: string;
}
/**
 * ListCommentsOutput is the structured result for list_comments.
 */
export interface ListCommentsOutput {
  /**
   * Comments is the ordered list of comments that matched the filters.
   */
  comments?: CommentView[];
}
/**
 * ResolveCommentInput is the typed input for resolve_comment.
 */
export interface ResolveCommentInput {
  /**
   * CommentID identifies which stored comment to resolve.
   */
  commentId: string;
  /**
   * Note is the optional resolution note.
   */
  note?: string;
}
/**
 * ResolveCommentOutput is the structured result for resolve_comment.
 */
export interface ResolveCommentOutput {
  /**
   * CommentID identifies the resolved comment.
   */
  commentId: string;
  /**
   * Resolved reports whether the comment is now resolved.
   */
  resolved: boolean;
}
/**
 * ChartSeries is one named data series for compile_chart.
 */
export interface ChartSeries {
  /**
   * Name labels the series (shown for line charts).
   */
  name?: string;
  /**
   * Values are the numeric data points.
   */
  values: number /* float64 */[];
}
/**
 * ChartSpec is the declarative chart description for compile_chart. The server
 * rasterizes it to a PNG (pure Go, no Chromium) and stores it as an asset.
 */
export interface ChartSpec {
  /**
   * Type selects the chart family: "bar", "line", or "pie".
   */
  type: string;
  /**
   * Title is the chart title (optional).
   */
  title?: string;
  /**
   * Labels are per-point category labels (required for bar and pie).
   */
  labels?: string[];
  /**
   * Series are the data series (bar/pie use the first; line plots each).
   */
  series: ChartSeries[];
}
/**
 * CompileChartInput is the model-facing input for compile_chart.
 */
export interface CompileChartInput {
  /**
   * Spec is the chart to rasterize.
   */
  spec: ChartSpec;
  /**
   * Caption overrides the chart node caption (defaults to the spec title).
   */
  caption?: string;
}
/**
 * CompileChartOutput returns a ready-to-use chart IR node plus its asset id.
 */
export interface CompileChartOutput {
  /**
   * Node is the chart IR node referencing the rasterized image by asset id.
   */
  node: Chart;
  /**
   * AssetID is the stored PNG's id ("asset://...").
   */
  assetId: string;
  /**
   * Warnings are non-fatal rasterization notes.
   */
  warnings?: string[];
}
/**
 * CompileCodeInput is the model-facing input for compile_code. The server
 * rasterizes the source to a PNG (pure-Go Go Mono font, no Chromium) and stores
 * it as an asset, returning a ready-to-use code_block IR node.
 */
export interface CompileCodeInput {
  /**
   * Code is the source text to rasterize.
   */
  code: string;
  /**
   * Language labels the snippet and is drawn as a small header badge (optional).
   */
  language?: string;
  /**
   * Caption overrides the code_block node caption (optional).
   */
  caption?: string;
}
/**
 * CompileCodeOutput returns a ready-to-use code_block IR node plus its asset id.
 */
export interface CompileCodeOutput {
  /**
   * Node is the code_block IR node referencing the rasterized image by asset id.
   */
  node: CodeBlock;
  /**
   * AssetID is the stored PNG's id ("asset://...").
   */
  assetId: string;
  /**
   * Warnings are non-fatal rasterization notes.
   */
  warnings?: string[];
}
/**
 * CompileMarkdownInput is the model-facing input for compile_markdown.
 */
export interface CompileMarkdownInput {
  /**
   * Markdown is the source text to parse into IR leaf nodes.
   */
  markdown: string;
}
/**
 * CompileMarkdownOutput returns the parsed IR leaf nodes and any parse warnings.
 */
export interface CompileMarkdownOutput {
  /**
   * Nodes are the parsed slide IR leaf nodes (headings, lists, quotes, prose).
   */
  nodes: SlideNode[];
  /**
   * Warnings are non-fatal parse notes.
   */
  warnings?: string[];
}
/**
 * CreateDeckInput is the typed input for create_deck.
 */
export interface CreateDeckInput {
  /**
   * Title is the initial deck title.
   */
  title: string;
  /**
   * Author is the initial deck author.
   */
  author?: string;
  /**
   * SoulID selects the design soul to apply to the deck.
   */
  soulId?: string;
}
/**
 * DeckKind identifies a deck-shaped output payload.
 */
export type DeckKind = string;
/**
 * DeckKindDeck marks a deck payload for future UI dispatch.
 */
export const DeckKindDeck: DeckKind = "deck";
/**
 * SlideSummary is the small preview payload for one slide.
 */
export interface SlideSummary {
  /**
   * SlideID is the stable slide identifier.
   */
  slideId: string;
  /**
   * Layout is the slide layout kind.
   */
  layout?: LayoutKind;
  /**
   * Title is a best-effort headline extracted from the slide content.
   */
  title?: string;
  /**
   * PreviewText is a short secondary text extracted from the slide content.
   */
  previewText?: string;
  /**
   * Revision is the deck revision snapshot this slide summary belongs to.
   */
  revision?: string;
}
/**
 * DeckChrome is the deck-level header/footer chrome contract.
 */
export interface DeckChrome {
  /**
   * Header is the header text shown on slides.
   */
  header?: string;
  /**
   * Footer is the footer text shown on slides.
   */
  footer?: string;
  /**
   * ShowOnCover controls whether chrome appears on the cover slide.
   */
  showOnCover?: boolean;
}
/**
 * DeckSection is one named grouping of slide IDs.
 */
export interface DeckSection {
  /**
   * Name is the section title.
   */
  name?: string;
  /**
   * SlideIDs is the ordered set of slide IDs in the section.
   */
  slideIds?: string[];
}
/**
 * CreateDeckOutput is the structured result for create_deck.
 */
export interface CreateDeckOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * Slides is the ordered preview summary of the deck's slides.
   */
  slides?: SlideSummary[];
}
/**
 * DeckSummary is the small list payload for one deck.
 */
export interface DeckSummary {
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * SlideCount is the number of slides in the deck.
   */
  slideCount: number /* int */;
  /**
   * UpdatedAt is the last mutation timestamp in ISO-8601 format.
   */
  updatedAt?: string;
}
/**
 * ListDecksInput is the typed input for list_decks.
 */
export interface ListDecksInput {
}
/**
 * ListDecksOutput is the structured result for list_decks.
 */
export interface ListDecksOutput {
  /**
   * Decks is every stored deck summary.
   */
  decks?: DeckSummary[];
}
/**
 * GetDeckInput is the typed input for get_deck.
 */
export interface GetDeckInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * GetDeckOutput is the structured result for get_deck.
 */
export interface GetDeckOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * Chrome is the deck-level header/footer chrome configuration.
   */
  chrome?: DeckChrome;
  /**
   * Sections is the deck's named grouping of slide IDs.
   */
  sections?: DeckSection[];
  /**
   * Slides is the ordered preview summary of the deck's slides.
   */
  slides?: SlideSummary[];
}
/**
 * DeleteDeckInput is the typed input for delete_deck.
 */
export interface DeleteDeckInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * DeleteDeckOutput is the structured result for delete_deck.
 */
export interface DeleteDeckOutput {
  /**
   * DeckID is the deleted deck identifier or slug input.
   */
  deckId: string;
  /**
   * Deleted reports whether the deck was removed.
   */
  deleted: boolean;
}
/**
 * SetDeckChromeInput is the typed input for set_deck_chrome.
 */
export interface SetDeckChromeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Chrome is the replacement chrome configuration.
   */
  chrome: DeckChrome;
}
/**
 * SetDeckChromeOutput is the structured result for set_deck_chrome.
 */
export interface SetDeckChromeOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Chrome is the applied deck-level chrome configuration.
   */
  chrome?: DeckChrome;
}
/**
 * SetDeckSectionsInput is the typed input for set_deck_sections.
 */
export interface SetDeckSectionsInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Sections is the replacement section grouping.
   */
  sections?: DeckSection[];
}
/**
 * SetDeckSectionsOutput is the structured result for set_deck_sections.
 */
export interface SetDeckSectionsOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Sections is the applied section grouping.
   */
  sections?: DeckSection[];
}
/**
 * IRPath is a structural path into a slide's node tree.
 */
export type IRPath = any[];
/**
 * EditSlideNodeInput is the typed input for edit_slide_node.
 */
export interface EditSlideNodeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the existing node to replace.
   */
  path?: IRPath;
  /**
   * Node is the replacement slide node as a JSON object with a "kind" discriminator.
   */
  node: { [key: string]: any};
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * EditSlideNodeOutput is the structured result for edit_slide_node.
 */
export interface EditSlideNodeOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * EditSlideFieldInput is the typed input for edit_slide_field.
 */
export interface EditSlideFieldInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the existing node whose field will be replaced.
   */
  path?: IRPath;
  /**
   * Field is the JSON field name to replace on the addressed node.
   */
  field: string;
  /**
   * Value is the replacement value for a string-valued field (e.g. a title,
   * label, or eyebrow). For rich text use patch_slide_text; for structured
   * fields (objects/arrays/numbers) replace the whole node via edit_slide_node.
   */
  value: string;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * EditSlideFieldOutput is the structured result for edit_slide_field.
 */
export interface EditSlideFieldOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * PatchSlideTextInput is the typed input for patch_slide_text.
 */
export interface PatchSlideTextInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the existing node whose text field will be replaced.
   */
  path?: IRPath;
  /**
   * Field is the RichText JSON field name to replace on the addressed node.
   */
  field: string;
  /**
   * Text is the plain text to encode as a single RichText run.
   */
  text: string;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * PatchSlideTextOutput is the structured result for patch_slide_text.
 */
export interface PatchSlideTextOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * InsertSlideNodeInput is the typed input for insert_slide_node.
 */
export interface InsertSlideNodeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the insertion point in a node slice.
   */
  path?: IRPath;
  /**
   * Node is the inserted slide node as a JSON object with a "kind" discriminator.
   */
  node: { [key: string]: any};
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * InsertSlideNodeOutput is the structured result for insert_slide_node.
 */
export interface InsertSlideNodeOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * RemoveSlideNodeInput is the typed input for remove_slide_node.
 */
export interface RemoveSlideNodeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the existing node to remove.
   */
  path?: IRPath;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * RemoveSlideNodeOutput is the structured result for remove_slide_node.
 */
export interface RemoveSlideNodeOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * DuplicateSlideNodeInput is the typed input for duplicate_slide_node.
 */
export interface DuplicateSlideNodeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * Path addresses the existing node to duplicate.
   */
  path?: IRPath;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * DuplicateSlideNodeOutput is the structured result for duplicate_slide_node.
 */
export interface DuplicateSlideNodeOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * MoveSlideNodeInput is the typed input for move_slide_node.
 */
export interface MoveSlideNodeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to edit.
   */
  slideId: string;
  /**
   * From addresses the existing node to move.
   */
  from?: IRPath;
  /**
   * To addresses the destination insertion point.
   */
  to?: IRPath;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * MoveSlideNodeOutput is the structured result for move_slide_node.
 */
export interface MoveSlideNodeOutput {
  /**
   * Slide is the stored edited slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * ExportDeckInput is the typed input for export_deck.
 */
export interface ExportDeckInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * ExportStats is the structured render summary for one exported deck.
 */
export interface ExportStats {
  /**
   * Slides is the number of rendered slides.
   */
  slides: number /* int */;
  /**
   * Shapes is the number of rendered shapes.
   */
  shapes: number /* int */;
  /**
   * Warnings is the ordered list of render warnings.
   */
  warnings?: string[];
}
/**
 * ExportDeckOutput is the structured result for export_deck.
 */
export interface ExportDeckOutput {
  /**
   * Path is the absolute workspace path of the exported .pptx file.
   */
  path: string;
  /**
   * ResourceURI is the readable deck:// resource URI for the exported .pptx file.
   */
  resourceUri: string;
  /**
   * Stats is the render summary for the export.
   */
  stats: ExportStats;
}
/**
 * ListResourcesInput is the typed input for list_resources.
 */
export interface ListResourcesInput {
}
/**
 * ResourceSummary is one exported deck resource summary.
 */
export interface ResourceSummary {
  /**
   * URI is the deck:// resource URI.
   */
  uri: string;
  /**
   * MIME is the resource MIME type.
   */
  mime: string;
  /**
   * Title is the human-readable exported filename.
   */
  title: string;
}
/**
 * ListResourcesOutput is the structured result for list_resources.
 */
export interface ListResourcesOutput {
  /**
   * Resources is one entry per exported deck file present on disk.
   */
  resources?: ResourceSummary[];
}
/**
 * GetResourceInput is the typed input for get_resource.
 */
export interface GetResourceInput {
  /**
   * URI is the absolute deck:// resource URI to resolve.
   */
  uri: string;
}
/**
 * GetResourceOutput is the structured result for get_resource.
 */
export interface GetResourceOutput {
  /**
   * URI is the requested deck:// resource URI.
   */
  uri: string;
  /**
   * MIME is the resource MIME type.
   */
  mime?: string;
  /**
   * Path is the absolute workspace path backing the resource.
   */
  path?: string;
  /**
   * Found reports whether the resource exists on disk.
   */
  found: boolean;
}
/**
 * AssetID names caller-supplied bytes resolved by the render-time
 * AssetResolver (mirrors pptx-go's scene.AssetID; see register-an-asset).
 * It is free-form: bare keys, content hashes, UUIDs, or "asset://<uuid>"
 * URIs — the engine imposes no scheme.
 */
export type AssetID = string;
/**
 * Crop is a per-edge image crop expressed as fractions in [0,1] (mirrors
 * pptx-go's builder Crop; see compose-a-scene → Validation: each edge in
 * [0,1], Left+Right < 1, Top+Bottom < 1). The zero value is no crop.
 */
export interface Crop {
  /**
   * Left is the fraction cropped from the left edge, in [0,1].
   */
  left?: number /* float64 */;
  /**
   * Top is the fraction cropped from the top edge, in [0,1].
   */
  top?: number /* float64 */;
  /**
   * Right is the fraction cropped from the right edge, in [0,1].
   */
  right?: number /* float64 */;
  /**
   * Bottom is the fraction cropped from the bottom edge, in [0,1].
   */
  bottom?: number /* float64 */;
}
/**
 * Fit selects how an image fills its slot (mirrors pptx-go's builder Fit;
 * FitFill is the default).
 */
export const FitFill = "fill";
export const FitNone = "none";
/**
 * Fit modes (wire values mirror the builder enum).
 */
export type Fit = typeof FitFill | typeof FitNone;
/**
 * Position is a 2D point in slide coordinates (mirrors pptx-go's builder
 * position types). Used by Decoration.Offset.
 */
export interface Position {
  /**
   * X is the horizontal coordinate (points).
   */
  x?: number /* float64 */;
  /**
   * Y is the vertical coordinate (points).
   */
  y?: number /* float64 */;
}
/**
 * Size is a 2D extent in slide coordinates (mirrors pptx-go's builder size
 * types). Used by Decoration.Size.
 */
export interface Size {
  /**
   * W is the width (points).
   */
  w?: number /* float64 */;
  /**
   * H is the height (points).
   */
  h?: number /* float64 */;
}
/**
 * FrameKind selects a device frame around an image (mirrors pptx-go's
 * scene.FrameKind). FrameName, when set, overrides Frame and selects a
 * WithFrameExtension frame.
 */
export type FrameKind = string;
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameNone: FrameKind = "none";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameBrowser: FrameKind = "browser";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FramePhone: FrameKind = "phone";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameDesktop: FrameKind = "desktop";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameLaptop: FrameKind = "laptop";
/**
 * Anchor names a slide anchor point for a Decoration (mirrors pptx-go's
 * scene.Anchor). The Offset is interpreted relative to this anchor.
 */
export const AnchorTopLeft = "top_left";
export const AnchorTop = "top";
export const AnchorTopRight = "top_right";
export const AnchorLeft = "left";
export const AnchorCenter = "center";
export const AnchorRight = "right";
export const AnchorBottomLeft = "bottom_left";
export const AnchorBottom = "bottom";
export const AnchorBottomRight = "bottom_right";
/**
 * Slide anchor positions (9-point compass; wire values are snake_case).
 */
export type Anchor = typeof AnchorTopLeft | typeof AnchorTop | typeof AnchorTopRight | typeof AnchorLeft | typeof AnchorCenter | typeof AnchorRight | typeof AnchorBottomLeft | typeof AnchorBottom | typeof AnchorBottomRight;
/**
 * Kind is the JSON "kind" discriminator that selects a concrete SlideNode.
 * Values are snake_case and match the pptx-go scene node (CONVENTIONS §2).
 */
export const KindHero = "hero";
export const KindHeading = "heading";
export const KindProse = "prose";
export const KindList = "list";
export const KindCallout = "callout";
export const KindTwoColumn = "two_column";
export const KindGrid = "grid";
export const KindCard = "card";
export const KindCardSection = "card_section";
/**
 * Node kinds implemented in Phase 1A.
 */
export type Kind = typeof KindHero | typeof KindHeading | typeof KindProse | typeof KindList | typeof KindCallout | typeof KindTwoColumn | typeof KindGrid | typeof KindCard | typeof KindCardSection;
export const KindDivider = "divider";
export const KindQuote = "quote";
export const KindChip = "chip";
export const KindArrow = "arrow";
export const KindSectionDivider = "section_divider";
export const KindTable = "table";
export const KindFlow = "flow";
export const KindImage = "image";
export const KindCodeBlock = "code_block";
export const KindChart = "chart";
export const KindDecoration = "decoration";
/**
 * Node kinds implemented in Phase 1B — the remaining leaf kinds (mirror the
 * compose-a-scene catalog). Wire values are snake_case per CONVENTIONS §2.
 */
export type Kind = typeof KindDivider | typeof KindQuote | typeof KindChip | typeof KindArrow | typeof KindSectionDivider | typeof KindTable | typeof KindFlow | typeof KindImage | typeof KindCodeBlock | typeof KindChart | typeof KindDecoration;
/**
 * LayoutKind is a slide's structural intent, mapping to a master layout
 * (mirrors pptx-go's scene.LayoutKind; CONVENTIONS §2).
 */
export type LayoutKind = string;
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutCover: LayoutKind = "cover";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutTitleContent: LayoutKind = "title_content";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutTwoColumn: LayoutKind = "two_column";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutCardGrid: LayoutKind = "card_grid";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutFullBleed: LayoutKind = "full_bleed";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutBlank: LayoutKind = "blank";
/**
 * SlideNode is the sealed-ish union of every slide IR node kind. The marker
 * method slideNodeKind is unexported, so only types in this package satisfy
 * the interface; the kind registry is the closed dispatch surface.
 * CONVENTIONS §3.
 */
export type SlideNode = any;
/**
 * CalloutKind selects a callout variant (mirrors pptx-go's scene.CalloutKind).
 */
export type CalloutKind = string;
/**
 * Callout variants.
 */
export const CalloutNote: CalloutKind = "note";
/**
 * Callout variants.
 */
export const CalloutWarning: CalloutKind = "warning";
/**
 * Callout variants.
 */
export const CalloutTip: CalloutKind = "tip";
/**
 * Callout variants.
 */
export const CalloutImportant: CalloutKind = "important";
/**
 * Callout is a highlighted note with a title and rich body. Mirror of
 * scene.Callout. The JSON field for the variant is "calloutKind" (not
 * "kind", which is the node discriminator).
 */
export interface Callout {
  /**
   * Kind is the callout variant.
   */
  calloutKind?: CalloutKind;
  /**
   * Title is the callout heading.
   */
  title?: string;
  /**
   * Body is the callout body content.
   */
  body?: RichText;
}
/**
 * BodyLayout selects how a card body stacks its children (mirrors pptx-go's
 * scene.BodyLayout; BodyVertical is the default).
 */
export type BodyLayout = string;
/**
 * Body layouts.
 */
export const BodyVertical: BodyLayout = "vertical";
/**
 * Body layouts.
 */
export const BodyHorizontal: BodyLayout = "horizontal";
/**
 * BorderStyle selects a card border style (mirrors scene.BorderStyle;
 * BorderDefault defers to the Outline flag).
 */
export type BorderStyle = string;
/**
 * Border styles.
 */
export const BorderDefault: BorderStyle = "default";
/**
 * Border styles.
 */
export const BorderNone: BorderStyle = "none";
/**
 * Border styles.
 */
export const BorderSolid: BorderStyle = "solid";
/**
 * Border styles.
 */
export const BorderAccent: BorderStyle = "accent";
/**
 * CardSize selects a card size variant (mirrors scene.CardSize).
 */
export const CardSizeMD = "md";
export const CardSizeSM = "sm";
export const CardSizeLG = "lg";
/**
 * Card sizes.
 */
export type CardSize = typeof CardSizeMD | typeof CardSizeSM | typeof CardSizeLG;
/**
 * CardLayout selects a card layout variant (mirrors scene.CardLayout).
 */
export const CardLayoutDefault = "default";
export const CardLayoutIconTop = "iconTop";
/**
 * Card layouts.
 */
export type CardLayout = typeof CardLayoutDefault | typeof CardLayoutIconTop;
/**
 * Card is an accent card holding a body of child nodes. All fields beyond
 * Header/Body are additive (zero values reproduce the default render).
 * Mirror of scene.Card. Children nest recursively.
 */
export interface Card {
  /**
   * Header is the card title.
   */
  header?: string;
  /**
   * Eyebrow is the small label above the header.
   */
  eyebrow?: string;
  /**
   * Icon is a closed-name curated/extension icon.
   */
  icon?: string;
  /**
   * HeaderPill is a pill-shaped badge in the header.
   */
  headerPill?: string;
  /**
   * Body is the card body children.
   */
  body?: SlideNode[];
  /**
   * BodyLayout stacks the body vertically (default) or horizontally.
   */
  bodyLayout?: BodyLayout;
  /**
   * Fill is the card surface color role.
   */
  fill?: ColorRole;
  /**
   * Outline enables a card border.
   */
  outline?: boolean;
  /**
   * BorderStyle selects the border style.
   */
  borderStyle?: BorderStyle;
  /**
   * Size is the card size variant.
   */
  size?: CardSize;
  /**
   * Layout is the card layout variant.
   */
  layout?: CardLayout;
  /**
   * Elevation is the card shadow role.
   */
  elevation?: ElevationRole;
}
/**
 * CardSection is a top-level card accepting grids, two-columns, or nested
 * cards. Body must be non-empty (validation, later unit). Mirror of
 * scene.CardSection. Children nest recursively.
 */
export interface CardSection {
  /**
   * Header is the section title.
   */
  header?: string;
  /**
   * Body is the section body children (must be non-empty).
   */
  body?: SlideNode[];
}
/**
 * DecorationKind selects a decoration's render path (mirrors pptx-go's
 * scene.DecorationKind). A preset decoration renders as native shapes; an
 * asset decoration renders as a PPTX picture (D-018).
 */
export type DecorationKind = string;
/**
 * Decoration kinds (wire values per compose-a-scene).
 */
export const DecorationPreset: DecorationKind = "preset";
/**
 * Decoration kinds (wire values per compose-a-scene).
 */
export const DecorationAsset: DecorationKind = "asset";
/**
 * Layer selects a decoration's z-order layer (mirrors pptx-go's
 * scene.Layer).
 */
export const LayerBackground = "background";
export const LayerForeground = "foreground";
/**
 * Decoration layers (wire values per compose-a-scene).
 */
export type Layer = typeof LayerBackground | typeof LayerForeground;
/**
 * Decoration is an ornamental element layered over a slide. A preset
 * decoration renders as native shapes; an asset decoration renders as a
 * PPTX picture from AssetID-resolved bytes. Mirror of pptx-go's
 * scene.Decoration. The JSON field for the variant is "decorationKind"
 * (not "kind", which is the node discriminator — CONVENTIONS §2).
 * Stage-1 validation: preset needs a Preset, asset needs an AssetID,
 * Opacity in [0,1] (Opacity 0 = opaque) — later unit.
 */
export interface Decoration {
  /**
   * Kind is the decoration variant (preset or asset).
   */
  decorationKind?: DecorationKind;
  /**
   * Preset is the curated ornament name (preset kind only).
   */
  preset?: string;
  /**
   * AssetID is the resolver key for the ornament bytes (asset kind only).
   */
  assetId?: AssetID;
  /**
   * Layer is the z-order layer.
   */
  layer?: Layer;
  /**
   * Anchor is the slide anchor the Offset is relative to.
   */
  anchor?: Anchor;
  /**
   * Offset is the position offset from the anchor.
   */
  offset?: Position;
  /**
   * Size is the decoration extent.
   */
  size?: Size;
  /**
   * Bleed extends the decoration to the slide edges.
   */
  bleed?: boolean;
  /**
   * Opacity is the decoration opacity in [0,1]; 0 means opaque.
   */
  opacity?: number /* float64 */;
  /**
   * Rotation is the clockwise rotation in degrees.
   */
  rotation?: number /* float64 */;
}
/**
 * Divider is a horizontal rule with surrounding spacing. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Divider.
 */
export interface Divider {
  /**
   * Spacing is the spacing token role above and below the rule.
   */
  spacing?: SpaceRole;
}
/**
 * FlowOrientation selects a flow's axis (mirrors pptx-go's
 * scene.FlowOrientation).
 */
export type FlowOrientation = string;
/**
 * Flow orientations (wire values per compose-a-scene).
 */
export const FlowHorizontal: FlowOrientation = "horizontal";
/**
 * Flow orientations (wire values per compose-a-scene).
 */
export const FlowVertical: FlowOrientation = "vertical";
/**
 * ConnectorKind selects the connector style between flow steps (mirrors
 * pptx-go's scene.ConnectorKind; ConnectorArrow is the default).
 */
export type ConnectorKind = string;
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorArrow: ConnectorKind = "arrow";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorArrowDashed: ConnectorKind = "arrow_dashed";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorCycle: ConnectorKind = "cycle";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorPlus: ConnectorKind = "plus";
/**
 * FlowStep is one step in a Flow. Mirror of scene.FlowStep. Icon is a closed-
 * name curated/extension icon (Stage-1 validated at render time).
 */
export interface FlowStep {
  /**
   * Label is the step heading.
   */
  label?: RichText;
  /**
   * Detail is the step body/description.
   */
  detail?: RichText;
  /**
   * Icon is a closed-name curated/extension icon name.
   */
  icon?: string;
}
/**
 * Flow is an ordered sequence of connected steps. Renders as native PPTX
 * shapes. Mirror of pptx-go's scene.Flow. At least one step is required
 * (validation, later unit).
 */
export interface Flow {
  /**
   * Orientation is the flow axis.
   */
  orientation?: FlowOrientation;
  /**
   * Steps is the ordered flow steps.
   */
  steps?: FlowStep[];
  /**
   * Connector is the connector style between steps.
   */
  connector?: ConnectorKind;
}
/**
 * Grid lays out children in a column grid. Columns is 2..4; Cells length is a
 * multiple of Columns; Ratio is empty or len == Columns (validation, later
 * unit). Mirror of scene.Grid. Children nest recursively.
 */
export interface Grid {
  /**
   * Columns is the cell count per row, 2..4.
   */
  columns?: number /* int */;
  /**
   * Ratio is an optional per-column width ratio; empty or len == Columns.
   */
  ratio?: number /* int */[];
  /**
   * Gap is the spacing between cells.
   */
  gap?: SpaceRole;
  /**
   * Cells is the grid children, a multiple of Columns.
   */
  cells?: SlideNode[];
}
/**
 * Hero is a cover/title slide node: an eyebrow, a title, and a subtitle.
 * Renders as native PPTX shapes. Mirror of pptx-go's scene.Hero.
 */
export interface Hero {
  /**
   * Eyebrow is the small label above the title.
   */
  eyebrow?: string;
  /**
   * Title is the headline.
   */
  title?: string;
  /**
   * Subtitle is the supporting line under the title.
   */
  subtitle?: string;
}
/**
 * Heading is a typed heading line at a 1..6 depth. Mirror of scene.Heading.
 */
export interface Heading {
  /**
   * Text is the heading content.
   */
  text?: RichText;
  /**
   * Level is the heading depth, 1..6.
   */
  level?: number /* int */;
}
/**
 * Prose is body text: an ordered list of paragraphs, each a RichText. Mirror
 * of scene.Prose.
 */
export interface Prose {
  /**
   * Paragraphs is the ordered body text, one RichText per paragraph.
   */
  paragraphs?: RichText[];
}
/**
 * ListKind selects a list style (mirrors pptx-go's scene.ListKind).
 */
export type ListKind = string;
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListBullet: ListKind = "bullet";
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListNumber: ListKind = "number";
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListChecklist: ListKind = "checklist";
/**
 * ListItem is one entry in a List. Mirror of scene.ListItem.
 */
export interface ListItem {
  /**
   * Text is the item's content.
   */
  text?: RichText;
  /**
   * Level is the nesting depth (0 = top-level).
   */
  level?: number /* int */;
  /**
   * Checked marks a checklist item as done (ListChecklist only).
   */
  checked?: boolean;
}
/**
 * List is a bullet, numbered, or checklist list. Mirror of scene.List. The
 * JSON field for the list style is "listKind" (not "kind", which is reserved
 * for the node discriminator — CONVENTIONS §2).
 */
export interface List {
  /**
   * Kind is the list style.
   */
  listKind?: ListKind;
  /**
   * Items is the ordered list entries.
   */
  items?: ListItem[];
}
/**
 * Image is a picture placed from caller-supplied bytes resolved by
 * AssetID. Renders as a PPTX picture (D-011). Mirror of pptx-go's
 * scene.Image. Stage-1 validation: non-empty AssetID and crop bounds (each
 * edge in [0,1], Left+Right < 1, Top+Bottom < 1) — later unit.
 */
export interface Image {
  /**
   * AssetID is the resolver key for the image bytes.
   */
  assetId?: AssetID;
  /**
   * Alt is the accessibility/alt-text description.
   */
  alt?: string;
  /**
   * Frame selects a device frame around the image.
   */
  frame?: FrameKind;
  /**
   * FrameName overrides Frame and selects a WithFrameExtension frame.
   */
  frameName?: string;
  /**
   * Crop is the per-edge crop fractions; the zero value is no crop.
   */
  crop?: Crop;
  /**
   * Fit selects how the image fills its slot; FitFill is the default.
   */
  fit?: Fit;
}
/**
 * CodeBlock is a source-code listing placed from a pre-rasterized image
 * resolved by AssetID (D-014). Renders as a PPTX picture. Mirror of
 * pptx-go's scene.CodeBlock. Stage-1 validation: non-empty AssetID — later
 * unit. Language and Caption are free-form and may be empty.
 */
export interface CodeBlock {
  /**
   * AssetID is the resolver key for the rendered code image.
   */
  assetId?: AssetID;
  /**
   * Language is the source language label (free-form).
   */
  language?: string;
  /**
   * Caption is the optional listing caption/filename.
   */
  caption?: string;
}
/**
 * Chart is a chart placed from a pre-rasterized image resolved by AssetID
 * (V1: image-shape; native c:chart is V2 — D-004). Renders as a PPTX
 * picture, or a labeled ChartPlaceholder when the asset is unresolved.
 * Mirror of pptx-go's scene.Chart. Stage-1 validation: non-empty AssetID —
 * later unit.
 */
export interface Chart {
  /**
   * AssetID is the resolver key for the chart image bytes.
   */
  assetId?: AssetID;
  /**
   * Caption is the optional chart caption.
   */
  caption?: string;
}
/**
 * ChipTone selects a chip's visual treatment (mirrors pptx-go's
 * scene.ChipTone).
 */
export type ChipTone = string;
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipTint: ChipTone = "tint";
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipSolid: ChipTone = "solid";
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipOutline: ChipTone = "outline";
/**
 * Chip is a compact label/badge. Renders as native PPTX shapes. Mirror of
 * pptx-go's scene.Chip. The JSON field for the tone is "tone" (the node
 * discriminator "kind" is reserved — CONVENTIONS §2).
 */
export interface Chip {
  /**
   * Label is the chip text.
   */
  label?: string;
  /**
   * Tone is the chip visual treatment.
   */
  tone?: ChipTone;
  /**
   * Color is the chip color role.
   */
  color?: ColorRole;
}
/**
 * ArrowDirection selects an arrow's direction (mirrors pptx-go's
 * scene.ArrowDirection).
 */
export type ArrowDirection = string;
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowRight: ArrowDirection = "right";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowLeft: ArrowDirection = "left";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowUp: ArrowDirection = "up";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowDown: ArrowDirection = "down";
/**
 * Arrow is a directional connector with an optional label. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Arrow.
 */
export interface Arrow {
  /**
   * Direction is the arrow direction.
   */
  direction?: ArrowDirection;
  /**
   * Label is the optional arrow label.
   */
  label?: string;
}
/**
 * SectionDivider is a full-bleed section break with an eyebrow and a label.
 * Renders as native PPTX shapes. Mirror of pptx-go's scene.SectionDivider.
 */
export interface SectionDivider {
  /**
   * Eyebrow is the small label above the section label.
   */
  eyebrow?: string;
  /**
   * Label is the section heading.
   */
  label?: string;
}
/**
 * Quote is a block quotation with an optional attribution. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Quote.
 */
export interface Quote {
  /**
   * Text is the quotation content.
   */
  text?: RichText;
  /**
   * Attribution is the optional source/author line.
   */
  attribution?: string;
}
/**
 * Table is a grid of cells with a header row and a caption. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Table. Each header cell and each
 * body cell is a RichText; every row width MUST equal the header width
 * (validation, later unit).
 */
export interface Table {
  /**
   * Headers is the header row, one RichText per column.
   */
  headers?: RichText[];
  /**
   * Rows is the body rows; each row is one RichText per column.
   */
  rows?: RichText[][];
  /**
   * Caption is the optional table caption.
   */
  caption?: string;
}
/**
 * ColumnRatio names a left:right width split (mirrors pptx-go's
 * scene.ColumnRatio; CONVENTIONS §2 uses "1:1").
 */
export type ColumnRatio = string;
/**
 * Column ratios.
 */
export const Ratio11: ColumnRatio = "1:1";
/**
 * Column ratios.
 */
export const Ratio12: ColumnRatio = "1:2";
/**
 * Column ratios.
 */
export const Ratio21: ColumnRatio = "2:1";
/**
 * TwoColumn splits a slide into left and right child columns. Both sides
 * must be non-empty (validation, later unit). Mirror of scene.TwoColumn.
 * Children are []SlideNode and nest recursively.
 */
export interface TwoColumn {
  /**
   * Ratio is the left:right width split.
   */
  ratio?: ColumnRatio;
  /**
   * Left is the left-column children.
   */
  left?: SlideNode[];
  /**
   * Right is the right-column children.
   */
  right?: SlideNode[];
}
/**
 * ColorRole names a surface fill color role (mirrors pptx-go's ColorRole;
 * the soul/theme resolves it to concrete RGB at render time).
 */
export type ColorRole = string;
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorCanvas: ColorRole = "canvas";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSurface: ColorRole = "surface";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSurfaceAlt: ColorRole = "surfaceAlt";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccent: ColorRole = "accent";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccentAlt: ColorRole = "accentAlt";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccentWarm: ColorRole = "accentWarm";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSuccess: ColorRole = "success";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorWarning: ColorRole = "warning";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorError: ColorRole = "error";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorInfo: ColorRole = "info";
/**
 * SpaceRole names a spacing token role (mirrors pptx-go's SpaceRole).
 */
export type SpaceRole = string;
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceXS: SpaceRole = "xs";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceSM: SpaceRole = "sm";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceMD: SpaceRole = "md";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceLG: SpaceRole = "lg";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceXL: SpaceRole = "xl";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const Space2XL: SpaceRole = "2xl";
/**
 * ElevationRole names a shadow elevation role (mirrors pptx-go's
 * ElevationRole).
 */
export type ElevationRole = string;
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationFlat: ElevationRole = "flat";
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationRaised: ElevationRole = "raised";
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationElevated: ElevationRole = "elevated";
/**
 * Slide is one slide: a stable ID, a structural layout, an ordered node tree,
 * and optional speaker notes. Nodes and Notes route through the codec
 * (CONVENTIONS §2/§3): marshaling injects each node's "kind" via the node's
 * own MarshalJSON; unmarshaling dispatches each node through
 * UnmarshalSlideNode (recursion) and each run through TextRun's unmarshaler.
 */
export interface Slide {
  /**
   * ID is the slide identifier (stable, agent/human addressable).
   */
  id: string;
  /**
   * Layout is the structural intent, mapping to a master layout.
   */
  layout?: LayoutKind;
  /**
   * Nodes is the slide's top-level node tree.
   */
  nodes?: SlideNode[];
  /**
   * Notes is the speaker notes.
   */
  notes?: RichText;
}
/**
 * SlideDoc is the deck-of-slides wrapper: a title plus an ordered slide list.
 * Slides route through Slide's own marshal/unmarshal, so node trees and notes
 * are codec-handled throughout.
 */
export interface SlideDoc {
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * Slides is the deck's slides, in order.
   */
  slides?: Slide[];
}
/**
 * AppBrand is the white-label brand configuration delivered to the UI surfaces.
 * It is resolved at server startup from the brand-token JSON (or defaults) and
 * lets a deployment re-skin the surfaces without a rebuild.
 */
export interface AppBrand {
  /**
   * Title is the product/brand name shown in surface chrome.
   */
  title?: string;
  /**
   * DefaultTheme is the built-in theme id selected by default
   * (deckard-white | deckard-dark | midnight | slate | editorial-sepia).
   */
  defaultTheme?: string;
  /**
   * Tokens are per-token "--app-*" overrides (key without the leading "--"),
   * applied over the selected preset.
   */
  tokens?: { [key: string]: string};
  /**
   * AllowThemeSwitch shows or hides the theme selector (false = locked brand).
   */
  allowThemeSwitch: boolean;
}
/**
 * ThumbNode is a glanceable descriptor of one IR node, rendered as a block in a
 * slide thumbnail. It carries just enough of the IR to compose a recognizable
 * preview — never the full node payload.
 */
export interface ThumbNode {
  /**
   * Kind is the IR node kind (heading, prose, list, callout, chart, ...).
   */
  kind: string;
  /**
   * Text is the primary text snippet (title, first line, label).
   */
  text?: string;
  /**
   * Detail is an optional secondary snippet (subtitle, attribution).
   */
  detail?: string;
  /**
   * Count is an item count for repeating nodes (list items, grid cells, steps).
   */
  count?: number /* int */;
  /**
   * Accent marks a node that renders in the accent color (callout, chip, accent card).
   */
  accent?: boolean;
}
/**
 * SlidePreview is one slide reduced to a thumbnail-renderable form.
 */
export interface SlidePreview {
  /**
   * ID is the stable slide identifier.
   */
  id: string;
  /**
   * Index is the zero-based position in the deck.
   */
  index: number /* int */;
  /**
   * Layout is the slide layout kind (cover, title_content, two_column, ...).
   */
  layout: string;
  /**
   * Title is a best-effort slide title for labelling the thumbnail.
   */
  title?: string;
  /**
   * Nodes are the top-level node descriptors composing the thumbnail.
   */
  nodes?: ThumbNode[];
}
/**
 * DeckPreviewInput drives the deck-preview surface.
 */
export interface DeckPreviewInput {
  /**
   * DeckID addresses the deck by stable ID or slug (empty = the active deck).
   */
  deckId?: string;
}
/**
 * DeckPreviewOutput is the structured payload the deck-preview surface renders.
 */
export interface DeckPreviewOutput {
  /**
   * State is the four-state page state (ready | empty | error | permission | loading).
   */
  state: string;
  /**
   * Message is the human-readable note for empty/error/permission states.
   */
  message?: string;
  /**
   * Brand is the white-label brand configuration for the surface.
   */
  brand: AppBrand;
  /**
   * Deck is the deck-level summary.
   */
  deck: DeckSummary;
  /**
   * Slides are the per-slide thumbnail descriptors in deck order.
   */
  slides?: SlidePreview[];
  /**
   * ResourceURI is the deck:// export resource for the [download] action.
   */
  resourceUri?: string;
}
/**
 * SaveAsTemplateInput is the typed input for save_as_template.
 */
export interface SaveAsTemplateInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to save as a recipe.
   */
  slideId: string;
  /**
   * Name is the caller-facing recipe name.
   */
  name: string;
  /**
   * Description is the optional recipe summary.
   */
  description?: string;
  /**
   * Tags are the optional recipe labels used for filtering.
   */
  tags?: string[];
}
/**
 * SaveAsTemplateOutput is the structured result for save_as_template.
 */
export interface SaveAsTemplateOutput {
  /**
   * RecipeID is the stored recipe identifier.
   */
  recipeId: string;
  /**
   * Name is the stored recipe name.
   */
  name: string;
}
/**
 * ListRecipesInput is the typed input for list_recipes.
 */
export interface ListRecipesInput {
  /**
   * Tag filters the returned recipes to one tag when set.
   */
  tag?: string;
  /**
   * SoulID is reserved for future soul-aware recipe selection.
   */
  soulId?: string;
}
/**
 * RecipeSummary is one list_recipes result item.
 */
export interface RecipeSummary {
  /**
   * RecipeID is the stable recipe identifier.
   */
  recipeId: string;
  /**
   * Name is the caller-facing recipe name.
   */
  name: string;
  /**
   * Tags are the recipe labels used for filtering.
   */
  tags?: string[];
  /**
   * Source reports whether the recipe is builtin or user-saved.
   */
  source?: string;
}
/**
 * ListRecipesOutput is the structured result for list_recipes.
 */
export interface ListRecipesOutput {
  /**
   * Recipes is the ordered recipe list, built-ins first then user recipes.
   */
  recipes?: RecipeSummary[];
}
/**
 * ApplyRecipeInput is the typed input for apply_recipe.
 */
export interface ApplyRecipeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * RecipeID is the stable recipe identifier to instantiate.
   */
  recipeId: string;
  /**
   * Position is the optional zero-based insertion index.
   */
  position?: number /* int */;
}
/**
 * ApplyRecipeOutput is the structured result for apply_recipe.
 */
export interface ApplyRecipeOutput {
  /**
   * SlideID is the inserted slide identifier assigned by the deck store.
   */
  slideId: string;
  /**
   * Slide is the stored slide snapshot created from the recipe.
   */
  slide: Slide;
}
/**
 * RichText is an ordered list of styled runs — the inline-text content type
 * used across the slide IR (CONVENTIONS §4). It marshals as a JSON array of
 * TextRun objects; each run is a flat { text, typeRole?, bold?, ... , color? }.
 */
export type RichText = TextRun[];
/**
 * TextRun is one styled run of text. Its JSON shape is flat (CONVENTIONS §4):
 * the Style fields are inlined into the run object and Color is omitted when
 * unset (meaning the token "primary").
 */
export interface TextRun {
  /**
   * Text is the literal run content.
   */
  Text: string;
  /**
   * Style carries typography and inline formatting.
   */
  Style: RunStyle;
  /**
   * Color is the run color; the zero value means the token "primary".
   */
  Color: TextColor;
}
/**
 * RunStyle mirrors pptx-go's scene.RunStyle: typography role plus inline
 * formatting flags and a link target.
 */
export interface RunStyle {
  /**
   * TypeRole selects a typography scale role (TypeBody, TypeH2, ...).
   */
  TypeRole: TypeRole;
  /**
   * Bold toggles bold weight.
   */
  Bold: boolean;
  /**
   * Italic toggles italic style.
   */
  Italic: boolean;
  /**
   * Underline toggles underline.
   */
  Underline: boolean;
  /**
   * Strike toggles strikethrough.
   */
  Strike: boolean;
  /**
   * Code marks the run as inline code (mono + tint).
   */
  Code: boolean;
  /**
   * Link marks the run as a hyperlink; Href is the target.
   */
  Link: boolean;
  /**
   * Href is the link URL when Link is true.
   */
  Href: string;
}
/**
 * TextColor is a run color: either a soul-bound token role (the documented
 * default) or a literal RGB escape hatch. The zero value is the token
 * "primary". JSON: { "token": "<role>" } or { "literal": "RRGGBB" }.
 */
export interface TextColor {
  /**
   * Token is a semantic text-color role resolved against the soul/theme.
   */
  token?: TextColorRole;
  /**
   * Literal is an explicit "RRGGBB" hex color bypassing the theme.
   */
  literal?: string;
}
/**
 * TextColorRole names a semantic text-color role (mirrors pptx-go's
 * TextColorRole; CONVENTIONS §4 lists the wire values verbatim).
 */
export type TextColorRole = string;
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextPrimary: TextColorRole = "primary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextSecondary: TextColorRole = "secondary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextTertiary: TextColorRole = "tertiary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextInverse: TextColorRole = "inverse";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextMuted: TextColorRole = "muted";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextAccent: TextColorRole = "accent";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextAccentAlt: TextColorRole = "accentAlt";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextSuccess: TextColorRole = "success";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextWarning: TextColorRole = "warning";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextError: TextColorRole = "error";
/**
 * TypeRole names a typography scale role (mirrors pptx-go's TypeRole; wire
 * values per CONVENTIONS §4: body|h1|h2|h3|code|...).
 */
export type TypeRole = string;
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeDisplay: TypeRole = "display";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH1: TypeRole = "h1";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH2: TypeRole = "h2";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH3: TypeRole = "h3";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH4: TypeRole = "h4";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH5: TypeRole = "h5";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeBody: TypeRole = "body";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeBodySmall: TypeRole = "bodySmall";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeCaption: TypeRole = "caption";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeMono: TypeRole = "mono";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeCode: TypeRole = "code";
/**
 * GetSessionInput is the typed input for get_session.
 */
export interface GetSessionInput {
}
/**
 * BuildInfo describes the running server build.
 */
export interface BuildInfo {
  /**
   * Name is the server binary name.
   */
  name: string;
  /**
   * Version is the server build version.
   */
  version: string;
}
/**
 * GetSessionOutput is the structured result for get_session.
 */
export interface GetSessionOutput {
  /**
   * ActiveDeckID is the currently active deck, if one is selected.
   */
  activeDeckId?: string;
  /**
   * ActiveSoulID is the currently active soul, if one is selected.
   */
  activeSoulId?: string;
  /**
   * OpenPanels is the ordered list of currently open panel identifiers.
   */
  openPanels: string[];
  /**
   * BuildInfo identifies the running Deckard build.
   */
  buildInfo: BuildInfo;
}
/**
 * SlideValidation is the structural validation result for one slide.
 */
export interface SlideValidation {
  /**
   * OK reports whether ValidateSlide returned no issues.
   */
  ok: boolean;
  /**
   * Issues is the flattened list of validation issue messages.
   */
  issues?: string[];
}
/**
 * AddSlideInput is the typed input for add_slide.
 */
export interface AddSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Slide is the slide snapshot to insert. Its ID is ignored on add.
   */
  slide: Slide;
  /**
   * Position is the optional zero-based insertion index.
   */
  position?: number /* int */;
}
/**
 * AddSlideOutput is the structured result for add_slide.
 */
export interface AddSlideOutput {
  /**
   * SlideID is the inserted slide identifier assigned by the store.
   */
  slideId: string;
  /**
   * Slide is the stored slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * UpdateSlideInput is the typed input for update_slide.
 */
export interface UpdateSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to replace.
   */
  slideId: string;
  /**
   * Slide is the replacement slide snapshot.
   */
  slide: Slide;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * UpdateSlideOutput is the structured result for update_slide.
 */
export interface UpdateSlideOutput {
  /**
   * SlideID is the updated slide identifier.
   */
  slideId: string;
  /**
   * Slide is the stored replacement slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * GetSlideInput is the typed input for get_slide.
 */
export interface GetSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to load.
   */
  slideId: string;
}
/**
 * GetSlideOutput is the structured result for get_slide.
 */
export interface GetSlideOutput {
  /**
   * SlideID is the loaded slide identifier.
   */
  slideId: string;
  /**
   * Slide is the loaded slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the loaded slide.
   */
  validation: SlideValidation;
}
/**
 * RemoveSlideInput is the typed input for remove_slide.
 */
export interface RemoveSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to delete.
   */
  slideId: string;
}
/**
 * RemoveSlideOutput is the structured result for remove_slide.
 */
export interface RemoveSlideOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Removed reports whether the slide was removed.
   */
  removed: boolean;
}
/**
 * ReorderSlidesInput is the typed input for reorder_slides.
 */
export interface ReorderSlidesInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Order is the complete ordered list of slide IDs.
   */
  order?: string[];
}
/**
 * ReorderSlidesOutput is the structured result for reorder_slides.
 */
export interface ReorderSlidesOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the reordered deck identifier.
   */
  deckId: string;
  /**
   * Slides is the ordered preview summary after reordering.
   */
  slides?: SlideSummary[];
}
/**
 * DuplicateSlideInput is the typed input for duplicate_slide.
 */
export interface DuplicateSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to copy.
   */
  slideId: string;
  /**
   * Position is the optional zero-based insertion index for the copy.
   */
  position?: number /* int */;
}
/**
 * DuplicateSlideOutput is the structured result for duplicate_slide.
 */
export interface DuplicateSlideOutput {
  /**
   * SlideID is the inserted duplicate slide identifier.
   */
  slideId: string;
  /**
   * Slide is the stored duplicate slide snapshot.
   */
  slide: Slide;
}
/**
 * SoulStatus filters or reports a soul lifecycle state.
 */
export type SoulStatus = string;
/**
 * TokenLayer identifies which theme layer produced one flattened design token.
 */
/**
 * TokenLayerSurface marks a surface color token.
 */
export const TokenLayerSurface = "surface";
/**
 * TokenLayerText marks a text color token.
 */
export const TokenLayerText = "text";
/**
 * TokenLayerTypography marks a typography token.
 */
export const TokenLayerTypography = "typography";
/**
 * TokenLayerSpacing marks a spacing token.
 */
export const TokenLayerSpacing = "spacing";
/**
 * TokenLayerRadius marks a radius token.
 */
export const TokenLayerRadius = "radius";
/**
 * TokenLayerElevation marks an elevation token.
 */
export const TokenLayerElevation = "elevation";
/**
 * TokenLayerExtension marks a non-native extension token.
 */
export const TokenLayerExtension = "extension";
export type TokenLayer = typeof TokenLayerSurface | typeof TokenLayerText | typeof TokenLayerTypography | typeof TokenLayerSpacing | typeof TokenLayerRadius | typeof TokenLayerElevation | typeof TokenLayerExtension;
/**
 * BootstrapSoulInput is the typed input for bootstrap_soul.
 */
export interface BootstrapSoulInput {
  /**
   * Name is the required soul name and the source of the stored soul ID.
   */
  name: string;
  /**
   * Description is an optional one-line soul summary.
   */
  description?: string;
  /**
   * Accent overrides the primary accent surface token as a six-digit hex string.
   */
  accent?: string;
  /**
   * AccentAlt overrides the alternate accent token as a six-digit hex string.
   */
  accentAlt?: string;
  /**
   * AccentWarm overrides the warm accent token as a six-digit hex string.
   */
  accentWarm?: string;
  /**
   * HeadingFont overrides the display and heading font family.
   */
  headingFont?: string;
  /**
   * BodyFont overrides the body and subheading font family.
   */
  bodyFont?: string;
  /**
   * MonoFont overrides the mono and code font family.
   */
  monoFont?: string;
}
/**
 * BootstrapSoulOutput is the structured result for bootstrap_soul.
 */
export interface BootstrapSoulOutput {
  /**
   * SoulID is the stored soul identifier.
   */
  soulId: string;
  /**
   * Name is the stored soul name.
   */
  name: string;
  /**
   * Status is the stored soul lifecycle state.
   */
  status?: SoulStatus;
  /**
   * TokenCount is the number of flattened resolved design tokens in the soul.
   */
  tokenCount: number /* int */;
}
/**
 * SoulOverride is one targeted refine instruction.
 */
export interface SoulOverride {
  /**
   * Category is the override family understood by the soul refiner.
   */
  category: string;
  /**
   * Token is the token name within the selected category.
   */
  token: string;
  /**
   * Value is the string form to apply to the selected token.
   */
  value: string;
}
/**
 * RefineSoulInput is the typed input for refine_soul.
 */
export interface RefineSoulInput {
  /**
   * SoulID addresses the stored soul to refine.
   */
  soulId: string;
  /**
   * Overrides is the ordered set of token overrides to apply.
   */
  overrides?: SoulOverride[];
}
/**
 * RefineSoulOutput is the structured result for refine_soul.
 */
export interface RefineSoulOutput {
  /**
   * SoulID is the refined soul identifier.
   */
  soulId: string;
  /**
   * Changed is the ordered set of category.token pairs overridden by this call.
   */
  changed?: string[];
  /**
   * TokenCount is the number of flattened resolved design tokens in the refined soul.
   */
  tokenCount: number /* int */;
}
/**
 * ListSoulsInput is the typed input for list_souls.
 */
export interface ListSoulsInput {
  /**
   * Status filters the list to one lifecycle state when set.
   */
  status?: SoulStatus;
}
/**
 * SoulSummary is the list payload for one stored soul.
 */
export interface SoulSummary {
  /**
   * SoulID is the stable soul identifier.
   */
  soulId: string;
  /**
   * Name is the human-facing soul name.
   */
  name: string;
  /**
   * Status is the soul lifecycle state.
   */
  status?: SoulStatus;
  /**
   * TokenCount is the number of flattened resolved design tokens in the soul.
   */
  tokenCount: number /* int */;
}
/**
 * ListSoulsOutput is the structured result for list_souls.
 */
export interface ListSoulsOutput {
  /**
   * Souls is every stored soul summary matching the filter.
   */
  souls?: SoulSummary[];
}
/**
 * GetSoulInput is the typed input for get_soul.
 */
export interface GetSoulInput {
  /**
   * SoulID addresses the stored soul to load.
   */
  soulId: string;
  /**
   * IncludeStyleGuide requests the soul voice guidance in the response.
   */
  includeStyleGuide?: boolean;
}
/**
 * SoulStyleGuide is the model-facing soul voice guidance.
 */
export interface SoulStyleGuide {
  /**
   * NorthStar is the one-line design intent.
   */
  northStar?: string;
  /**
   * Do lists encouraged authoring behaviors.
   */
  do?: string[];
  /**
   * Dont lists discouraged authoring behaviors.
   */
  dont?: string[];
}
/**
 * TokenEntry is one flattened design token from a soul theme.
 */
export interface TokenEntry {
  /**
   * Name is the stable token name within its layer.
   */
  name: string;
  /**
   * Value is the string form of the resolved token value.
   */
  value: string;
  /**
   * Layer identifies which token family produced this entry.
   */
  layer: TokenLayer;
}
/**
 * GetSoulOutput is the structured result for get_soul.
 */
export interface GetSoulOutput {
  /**
   * SoulID is the loaded soul identifier.
   */
  soulId: string;
  /**
   * Name is the loaded soul name.
   */
  name: string;
  /**
   * Status is the loaded soul lifecycle state.
   */
  status?: SoulStatus;
  /**
   * Description is the optional one-line soul summary.
   */
  description?: string;
  /**
   * Tokens is the flattened token list for the soul theme.
   */
  tokens?: TokenEntry[];
  /**
   * StyleGuide is the optional voice guidance for the soul.
   */
  styleGuide?: SoulStyleGuide;
}
/**
 * GetDesignTokensInput is the typed input for get_design_tokens.
 */
export interface GetDesignTokensInput {
  /**
   * SoulID addresses the stored soul whose flattened tokens should be returned.
   */
  soulId: string;
}
/**
 * GetDesignTokensOutput is the structured result for get_design_tokens.
 */
export interface GetDesignTokensOutput {
  /**
   * Tokens is the flattened token list for the soul theme.
   */
  tokens?: TokenEntry[];
}
/**
 * SurfaceKind identifies which UI surface a surface tool's structured output
 * is shaped for. The discriminator lets a single dispatcher branch on the
 * payload shape without sniffing its fields.
 */
/**
 * SurfaceKindOverview marks the deck-overview hydration payload.
 */
export const SurfaceKindOverview = "overview";
/**
 * SurfaceKindEditor marks the single-slide editor payload.
 */
export const SurfaceKindEditor = "editor";
/**
 * SurfaceKindState marks the aggregate deck-state hydration payload.
 */
export const SurfaceKindState = "state";
/**
 * SurfaceKindActiveWorkspace marks the active-workspace session payload.
 */
export const SurfaceKindActiveWorkspace = "active_workspace";
export type SurfaceKind = typeof SurfaceKindOverview | typeof SurfaceKindEditor | typeof SurfaceKindState | typeof SurfaceKindActiveWorkspace;
/**
 * GetDeckOverviewInput is the typed input for get_deck_overview.
 */
export interface GetDeckOverviewInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * DeckOverviewSection is one named section of the deck overview.
 */
export interface DeckOverviewSection {
  /**
   * Name is the section title.
   */
  name?: string;
  /**
   * SlideIDs is the ordered set of slide IDs in the section.
   */
  slideIds?: string[];
}
/**
 * GetDeckOverviewOutput is the structured result for get_deck_overview.
 */
export interface GetDeckOverviewOutput {
  /**
   * Kind identifies this payload as the overview surface result.
   */
  kind: SurfaceKind;
  /**
   * State is the four-state page state (ready | empty | error | permission | loading).
   */
  state?: string;
  /**
   * Message is the human-readable note for empty/error/permission states.
   */
  message?: string;
  /**
   * DeckID is the resolved deck identifier.
   */
  deckId: string;
  /**
   * Title is the deck title at fetch time.
   */
  title?: string;
  /**
   * Sections is the deck's named section grouping.
   */
  sections?: DeckOverviewSection[];
  /**
   * Slides is the ordered preview summary of the deck's slides.
   */
  slides?: SlideSummary[];
  /**
   * Brand is the white-label brand config for the surface chrome/theme.
   */
  brand: AppBrand;
}
/**
 * OpenSlideEditorInput is the typed input for open_slide_editor.
 */
export interface OpenSlideEditorInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to open in the editor.
   */
  slideId: string;
}
/**
 * OpenSlideEditorOutput is the structured result for open_slide_editor.
 */
export interface OpenSlideEditorOutput {
  /**
   * Kind identifies this payload as the editor surface result.
   */
  kind: SurfaceKind;
  /**
   * State is the four-state page state (ready | empty | error | permission | loading).
   */
  state?: string;
  /**
   * Message is the human-readable note for empty/error/permission states.
   */
  message?: string;
  /**
   * DeckID is the deck the slide belongs to (needed for the node-edit tools).
   */
  deckId: string;
  /**
   * SlideID is the slide identifier opened in the editor.
   */
  slideId: string;
  /**
   * IR is the slide's full IR snapshot for the editor.
   */
  ir: Slide;
  /**
   * SoulID is the design soul the deck is bound to.
   */
  soulId?: string;
  /**
   * Validation is the structural validation result for the slide IR.
   */
  validation: SlideValidation;
  /**
   * Brand is the white-label brand config for the surface chrome/theme.
   */
  brand: AppBrand;
  /**
   * Layout is the server-computed node geometry for the canvas (EMU boxes,
   * mirroring the renderer) — the editor paints this, never re-computes layout.
   */
  layout: SlideLayout;
  /**
   * Palette is the deck soul's resolved colors + fonts so the canvas paints in
   * the deck's visual language (matching the export).
   */
  palette: SoulPalette;
}
/**
 * SetActiveWorkspaceInput is the typed input for set_active_workspace.
 */
export interface SetActiveWorkspaceInput {
  /**
   * DeckID is the optional deck ID to mark as the active workspace deck.
   */
  deckId?: string;
  /**
   * SoulID is the optional soul ID to mark as the active workspace soul.
   */
  soulId?: string;
}
/**
 * SetActiveWorkspaceOutput is the structured result for set_active_workspace.
 */
export interface SetActiveWorkspaceOutput {
  /**
   * Kind identifies this payload as the active-workspace write result.
   */
  kind: SurfaceKind;
  /**
   * ActiveDeckID is the new active deck identifier.
   */
  activeDeckId?: string;
  /**
   * ActiveSoulID is the new active soul identifier.
   */
  activeSoulId?: string;
}
/**
 * StyleFinding is one structured validation finding behind a StyleScore.
 */
export interface StyleFinding {
  /**
   * Category groups the finding: structural, contrast, typography, spacing, token.
   */
  category: string;
  /**
   * Severity is "error" (blocks export) or "warning" (advisory).
   */
  severity: string;
  /**
   * Message is the human-readable description.
   */
  message: string;
  /**
   * Path is the optional IR node path the finding refers to.
   */
  path?: string;
}
/**
 * ValidateSlideIRInput is the typed input for validate_slide_ir.
 */
export interface ValidateSlideIRInput {
  /**
   * Slide is the slide snapshot to validate without storage.
   */
  slide: Slide;
  /**
   * SoulID is the optional soul context; when set, contrast and overflow run
   * against that soul's theme (otherwise only structural checks run).
   */
  soulId?: string;
}
/**
 * ValidateSlideIROutput is the structured result for validate_slide_ir.
 */
export interface ValidateSlideIROutput {
  /**
   * OK reports whether the slide passed (no errors).
   */
  ok: boolean;
  /**
   * Score is the weighted StyleScore in [0,1].
   */
  score: number /* float64 */;
  /**
   * Issues is the flattened list of validation issue messages.
   */
  issues?: string[];
  /**
   * Findings is the structured list of issues with category and severity.
   */
  findings?: StyleFinding[];
}
/**
 * ValidateSlideInput is the typed input for validate_slide.
 */
export interface ValidateSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to validate.
   */
  slideId: string;
}
/**
 * ValidateSlideOutput is the structured result for validate_slide.
 */
export interface ValidateSlideOutput {
  /**
   * SlideID is the validated slide identifier.
   */
  slideId: string;
  /**
   * OK reports whether the slide passed (no errors).
   */
  ok: boolean;
  /**
   * Score is the weighted StyleScore in [0,1].
   */
  score: number /* float64 */;
  /**
   * Issues is the flattened list of validation issue messages.
   */
  issues?: string[];
  /**
   * Findings is the structured list of issues with category and severity.
   */
  findings?: StyleFinding[];
}
/**
 * ValidateDeckForExportInput is the typed input for validate_deck_for_export.
 */
export interface ValidateDeckForExportInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * DeckSlideValidation is the per-slide validation result for deck export checks.
 */
export interface DeckSlideValidation {
  /**
   * SlideID is the validated slide identifier.
   */
  slideId: string;
  /**
   * OK reports whether the slide passed (no errors).
   */
  ok: boolean;
  /**
   * Score is the per-slide weighted StyleScore in [0,1].
   */
  score: number /* float64 */;
  /**
   * Issues is the flattened list of validation issue messages.
   */
  issues?: string[];
}
/**
 * ValidateDeckForExportOutput is the structured result for validate_deck_for_export.
 */
export interface ValidateDeckForExportOutput {
  /**
   * OK reports whether the deck passed (no errors anywhere).
   */
  ok: boolean;
  /**
   * Score is the deck-wide weighted StyleScore in [0,1].
   */
  score: number /* float64 */;
  /**
   * PerSlide is the validation result for each slide in deck order.
   */
  perSlide?: DeckSlideValidation[];
  /**
   * Blockers is the flattened list of slide-scoped export blockers.
   */
  blockers?: string[];
  /**
   * Findings is the structured list of deck-wide issues (incl. contrast/overflow).
   */
  findings?: StyleFinding[];
}
