// Code generated by dockyard; DO NOT EDIT.
//
// TypeScript contract types — the UI-facing half of the Design A codegen
// pipeline (RFC §6.2). Generated from the Go contract structs by github.com/
// gzuidhof/tygo. The Go struct is the single source of truth (P1); regenerate
// with `dockyard generate` and never edit this file by hand.

/**
 * CreateDeckInput is the typed input for create_deck.
 */
export interface CreateDeckInput {
  /**
   * Title is the initial deck title.
   */
  title: string;
  /**
   * Author is the initial deck author.
   */
  author?: string;
  /**
   * SoulID selects the design soul to apply to the deck.
   */
  soulId?: string;
}
/**
 * DeckKind identifies a deck-shaped output payload.
 */
export type DeckKind = string;
/**
 * DeckKindDeck marks a deck payload for future UI dispatch.
 */
export const DeckKindDeck: DeckKind = "deck";
/**
 * SlideSummary is the small preview payload for one slide.
 */
export interface SlideSummary {
  /**
   * SlideID is the stable slide identifier.
   */
  slideId: string;
  /**
   * Layout is the slide layout kind.
   */
  layout?: LayoutKind;
  /**
   * Title is a best-effort headline extracted from the slide content.
   */
  title?: string;
  /**
   * PreviewText is a short secondary text extracted from the slide content.
   */
  previewText?: string;
  /**
   * Revision is the deck revision snapshot this slide summary belongs to.
   */
  revision?: string;
}
/**
 * DeckChrome is the deck-level header/footer chrome contract.
 */
export interface DeckChrome {
  /**
   * Header is the header text shown on slides.
   */
  header?: string;
  /**
   * Footer is the footer text shown on slides.
   */
  footer?: string;
  /**
   * ShowOnCover controls whether chrome appears on the cover slide.
   */
  showOnCover?: boolean;
}
/**
 * DeckSection is one named grouping of slide IDs.
 */
export interface DeckSection {
  /**
   * Name is the section title.
   */
  name?: string;
  /**
   * SlideIDs is the ordered set of slide IDs in the section.
   */
  slideIds?: string[];
}
/**
 * CreateDeckOutput is the structured result for create_deck.
 */
export interface CreateDeckOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * Slides is the ordered preview summary of the deck's slides.
   */
  slides?: SlideSummary[];
}
/**
 * DeckSummary is the small list payload for one deck.
 */
export interface DeckSummary {
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * SlideCount is the number of slides in the deck.
   */
  slideCount: number /* int */;
  /**
   * UpdatedAt is the last mutation timestamp in ISO-8601 format.
   */
  updatedAt?: string;
}
/**
 * ListDecksInput is the typed input for list_decks.
 */
export interface ListDecksInput {
}
/**
 * ListDecksOutput is the structured result for list_decks.
 */
export interface ListDecksOutput {
  /**
   * Decks is every stored deck summary.
   */
  decks?: DeckSummary[];
}
/**
 * GetDeckInput is the typed input for get_deck.
 */
export interface GetDeckInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * GetDeckOutput is the structured result for get_deck.
 */
export interface GetDeckOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the stable deck identifier.
   */
  deckId: string;
  /**
   * Slug is the human-readable unique lookup key.
   */
  slug: string;
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * SoulID is the design soul applied to the deck.
   */
  soulId?: string;
  /**
   * Chrome is the deck-level header/footer chrome configuration.
   */
  chrome?: DeckChrome;
  /**
   * Sections is the deck's named grouping of slide IDs.
   */
  sections?: DeckSection[];
  /**
   * Slides is the ordered preview summary of the deck's slides.
   */
  slides?: SlideSummary[];
}
/**
 * DeleteDeckInput is the typed input for delete_deck.
 */
export interface DeleteDeckInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
}
/**
 * DeleteDeckOutput is the structured result for delete_deck.
 */
export interface DeleteDeckOutput {
  /**
   * DeckID is the deleted deck identifier or slug input.
   */
  deckId: string;
  /**
   * Deleted reports whether the deck was removed.
   */
  deleted: boolean;
}
/**
 * SetDeckChromeInput is the typed input for set_deck_chrome.
 */
export interface SetDeckChromeInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Chrome is the replacement chrome configuration.
   */
  chrome: DeckChrome;
}
/**
 * SetDeckChromeOutput is the structured result for set_deck_chrome.
 */
export interface SetDeckChromeOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Chrome is the applied deck-level chrome configuration.
   */
  chrome?: DeckChrome;
}
/**
 * SetDeckSectionsInput is the typed input for set_deck_sections.
 */
export interface SetDeckSectionsInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Sections is the replacement section grouping.
   */
  sections?: DeckSection[];
}
/**
 * SetDeckSectionsOutput is the structured result for set_deck_sections.
 */
export interface SetDeckSectionsOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Sections is the applied section grouping.
   */
  sections?: DeckSection[];
}
/**
 * AssetID names caller-supplied bytes resolved by the render-time
 * AssetResolver (mirrors pptx-go's scene.AssetID; see register-an-asset).
 * It is free-form: bare keys, content hashes, UUIDs, or "asset://<uuid>"
 * URIs — the engine imposes no scheme.
 */
export type AssetID = string;
/**
 * Crop is a per-edge image crop expressed as fractions in [0,1] (mirrors
 * pptx-go's builder Crop; see compose-a-scene → Validation: each edge in
 * [0,1], Left+Right < 1, Top+Bottom < 1). The zero value is no crop.
 */
export interface Crop {
  /**
   * Left is the fraction cropped from the left edge, in [0,1].
   */
  left?: number /* float64 */;
  /**
   * Top is the fraction cropped from the top edge, in [0,1].
   */
  top?: number /* float64 */;
  /**
   * Right is the fraction cropped from the right edge, in [0,1].
   */
  right?: number /* float64 */;
  /**
   * Bottom is the fraction cropped from the bottom edge, in [0,1].
   */
  bottom?: number /* float64 */;
}
/**
 * Fit selects how an image fills its slot (mirrors pptx-go's builder Fit;
 * FitFill is the default).
 */
export const FitFill = "fill";
export const FitNone = "none";
/**
 * Fit modes (wire values mirror the builder enum).
 */
export type Fit = typeof FitFill | typeof FitNone;
/**
 * Position is a 2D point in slide coordinates (mirrors pptx-go's builder
 * position types). Used by Decoration.Offset.
 */
export interface Position {
  /**
   * X is the horizontal coordinate (points).
   */
  x?: number /* float64 */;
  /**
   * Y is the vertical coordinate (points).
   */
  y?: number /* float64 */;
}
/**
 * Size is a 2D extent in slide coordinates (mirrors pptx-go's builder size
 * types). Used by Decoration.Size.
 */
export interface Size {
  /**
   * W is the width (points).
   */
  w?: number /* float64 */;
  /**
   * H is the height (points).
   */
  h?: number /* float64 */;
}
/**
 * FrameKind selects a device frame around an image (mirrors pptx-go's
 * scene.FrameKind). FrameName, when set, overrides Frame and selects a
 * WithFrameExtension frame.
 */
export type FrameKind = string;
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameNone: FrameKind = "none";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameBrowser: FrameKind = "browser";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FramePhone: FrameKind = "phone";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameDesktop: FrameKind = "desktop";
/**
 * Frame kinds (wire values per compose-a-scene).
 */
export const FrameLaptop: FrameKind = "laptop";
/**
 * Anchor names a slide anchor point for a Decoration (mirrors pptx-go's
 * scene.Anchor). The Offset is interpreted relative to this anchor.
 */
export const AnchorTopLeft = "top_left";
export const AnchorTop = "top";
export const AnchorTopRight = "top_right";
export const AnchorLeft = "left";
export const AnchorCenter = "center";
export const AnchorRight = "right";
export const AnchorBottomLeft = "bottom_left";
export const AnchorBottom = "bottom";
export const AnchorBottomRight = "bottom_right";
/**
 * Slide anchor positions (9-point compass; wire values are snake_case).
 */
export type Anchor = typeof AnchorTopLeft | typeof AnchorTop | typeof AnchorTopRight | typeof AnchorLeft | typeof AnchorCenter | typeof AnchorRight | typeof AnchorBottomLeft | typeof AnchorBottom | typeof AnchorBottomRight;
/**
 * Kind is the JSON "kind" discriminator that selects a concrete SlideNode.
 * Values are snake_case and match the pptx-go scene node (CONVENTIONS §2).
 */
export const KindHero = "hero";
export const KindHeading = "heading";
export const KindProse = "prose";
export const KindList = "list";
export const KindCallout = "callout";
export const KindTwoColumn = "two_column";
export const KindGrid = "grid";
export const KindCard = "card";
export const KindCardSection = "card_section";
/**
 * Node kinds implemented in Phase 1A.
 */
export type Kind = typeof KindHero | typeof KindHeading | typeof KindProse | typeof KindList | typeof KindCallout | typeof KindTwoColumn | typeof KindGrid | typeof KindCard | typeof KindCardSection;
export const KindDivider = "divider";
export const KindQuote = "quote";
export const KindChip = "chip";
export const KindArrow = "arrow";
export const KindSectionDivider = "section_divider";
export const KindTable = "table";
export const KindFlow = "flow";
export const KindImage = "image";
export const KindCodeBlock = "code_block";
export const KindChart = "chart";
export const KindDecoration = "decoration";
/**
 * Node kinds implemented in Phase 1B — the remaining leaf kinds (mirror the
 * compose-a-scene catalog). Wire values are snake_case per CONVENTIONS §2.
 */
export type Kind = typeof KindDivider | typeof KindQuote | typeof KindChip | typeof KindArrow | typeof KindSectionDivider | typeof KindTable | typeof KindFlow | typeof KindImage | typeof KindCodeBlock | typeof KindChart | typeof KindDecoration;
/**
 * LayoutKind is a slide's structural intent, mapping to a master layout
 * (mirrors pptx-go's scene.LayoutKind; CONVENTIONS §2).
 */
export type LayoutKind = string;
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutCover: LayoutKind = "cover";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutTitleContent: LayoutKind = "title_content";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutTwoColumn: LayoutKind = "two_column";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutCardGrid: LayoutKind = "card_grid";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutFullBleed: LayoutKind = "full_bleed";
/**
 * Slide layouts (wire values per CONVENTIONS §2).
 */
export const LayoutBlank: LayoutKind = "blank";
/**
 * SlideNode is the sealed-ish union of every slide IR node kind. The marker
 * method slideNodeKind is unexported, so only types in this package satisfy
 * the interface; the kind registry is the closed dispatch surface.
 * CONVENTIONS §3.
 */
export type SlideNode = any;
/**
 * CalloutKind selects a callout variant (mirrors pptx-go's scene.CalloutKind).
 */
export type CalloutKind = string;
/**
 * Callout variants.
 */
export const CalloutNote: CalloutKind = "note";
/**
 * Callout variants.
 */
export const CalloutWarning: CalloutKind = "warning";
/**
 * Callout variants.
 */
export const CalloutTip: CalloutKind = "tip";
/**
 * Callout variants.
 */
export const CalloutImportant: CalloutKind = "important";
/**
 * Callout is a highlighted note with a title and rich body. Mirror of
 * scene.Callout. The JSON field for the variant is "calloutKind" (not
 * "kind", which is the node discriminator).
 */
export interface Callout {
  /**
   * Kind is the callout variant.
   */
  calloutKind?: CalloutKind;
  /**
   * Title is the callout heading.
   */
  title?: string;
  /**
   * Body is the callout body content.
   */
  body?: RichText;
}
/**
 * BodyLayout selects how a card body stacks its children (mirrors pptx-go's
 * scene.BodyLayout; BodyVertical is the default).
 */
export type BodyLayout = string;
/**
 * Body layouts.
 */
export const BodyVertical: BodyLayout = "vertical";
/**
 * Body layouts.
 */
export const BodyHorizontal: BodyLayout = "horizontal";
/**
 * BorderStyle selects a card border style (mirrors scene.BorderStyle;
 * BorderDefault defers to the Outline flag).
 */
export type BorderStyle = string;
/**
 * Border styles.
 */
export const BorderDefault: BorderStyle = "default";
/**
 * Border styles.
 */
export const BorderNone: BorderStyle = "none";
/**
 * Border styles.
 */
export const BorderSolid: BorderStyle = "solid";
/**
 * Border styles.
 */
export const BorderAccent: BorderStyle = "accent";
/**
 * CardSize selects a card size variant (mirrors scene.CardSize).
 */
export const CardSizeMD = "md";
export const CardSizeSM = "sm";
export const CardSizeLG = "lg";
/**
 * Card sizes.
 */
export type CardSize = typeof CardSizeMD | typeof CardSizeSM | typeof CardSizeLG;
/**
 * CardLayout selects a card layout variant (mirrors scene.CardLayout).
 */
export const CardLayoutDefault = "default";
export const CardLayoutIconTop = "iconTop";
/**
 * Card layouts.
 */
export type CardLayout = typeof CardLayoutDefault | typeof CardLayoutIconTop;
/**
 * Card is an accent card holding a body of child nodes. All fields beyond
 * Header/Body are additive (zero values reproduce the default render).
 * Mirror of scene.Card. Children nest recursively.
 */
export interface Card {
  /**
   * Header is the card title.
   */
  header?: string;
  /**
   * Eyebrow is the small label above the header.
   */
  eyebrow?: string;
  /**
   * Icon is a closed-name curated/extension icon.
   */
  icon?: string;
  /**
   * HeaderPill is a pill-shaped badge in the header.
   */
  headerPill?: string;
  /**
   * Body is the card body children.
   */
  body?: SlideNode[];
  /**
   * BodyLayout stacks the body vertically (default) or horizontally.
   */
  bodyLayout?: BodyLayout;
  /**
   * Fill is the card surface color role.
   */
  fill?: ColorRole;
  /**
   * Outline enables a card border.
   */
  outline?: boolean;
  /**
   * BorderStyle selects the border style.
   */
  borderStyle?: BorderStyle;
  /**
   * Size is the card size variant.
   */
  size?: CardSize;
  /**
   * Layout is the card layout variant.
   */
  layout?: CardLayout;
  /**
   * Elevation is the card shadow role.
   */
  elevation?: ElevationRole;
}
/**
 * CardSection is a top-level card accepting grids, two-columns, or nested
 * cards. Body must be non-empty (validation, later unit). Mirror of
 * scene.CardSection. Children nest recursively.
 */
export interface CardSection {
  /**
   * Header is the section title.
   */
  header?: string;
  /**
   * Body is the section body children (must be non-empty).
   */
  body?: SlideNode[];
}
/**
 * DecorationKind selects a decoration's render path (mirrors pptx-go's
 * scene.DecorationKind). A preset decoration renders as native shapes; an
 * asset decoration renders as a PPTX picture (D-018).
 */
export type DecorationKind = string;
/**
 * Decoration kinds (wire values per compose-a-scene).
 */
export const DecorationPreset: DecorationKind = "preset";
/**
 * Decoration kinds (wire values per compose-a-scene).
 */
export const DecorationAsset: DecorationKind = "asset";
/**
 * Layer selects a decoration's z-order layer (mirrors pptx-go's
 * scene.Layer).
 */
export const LayerBackground = "background";
export const LayerForeground = "foreground";
/**
 * Decoration layers (wire values per compose-a-scene).
 */
export type Layer = typeof LayerBackground | typeof LayerForeground;
/**
 * Decoration is an ornamental element layered over a slide. A preset
 * decoration renders as native shapes; an asset decoration renders as a
 * PPTX picture from AssetID-resolved bytes. Mirror of pptx-go's
 * scene.Decoration. The JSON field for the variant is "decorationKind"
 * (not "kind", which is the node discriminator — CONVENTIONS §2).
 * Stage-1 validation: preset needs a Preset, asset needs an AssetID,
 * Opacity in [0,1] (Opacity 0 = opaque) — later unit.
 */
export interface Decoration {
  /**
   * Kind is the decoration variant (preset or asset).
   */
  decorationKind?: DecorationKind;
  /**
   * Preset is the curated ornament name (preset kind only).
   */
  preset?: string;
  /**
   * AssetID is the resolver key for the ornament bytes (asset kind only).
   */
  assetId?: AssetID;
  /**
   * Layer is the z-order layer.
   */
  layer?: Layer;
  /**
   * Anchor is the slide anchor the Offset is relative to.
   */
  anchor?: Anchor;
  /**
   * Offset is the position offset from the anchor.
   */
  offset?: Position;
  /**
   * Size is the decoration extent.
   */
  size?: Size;
  /**
   * Bleed extends the decoration to the slide edges.
   */
  bleed?: boolean;
  /**
   * Opacity is the decoration opacity in [0,1]; 0 means opaque.
   */
  opacity?: number /* float64 */;
  /**
   * Rotation is the clockwise rotation in degrees.
   */
  rotation?: number /* float64 */;
}
/**
 * Divider is a horizontal rule with surrounding spacing. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Divider.
 */
export interface Divider {
  /**
   * Spacing is the spacing token role above and below the rule.
   */
  spacing?: SpaceRole;
}
/**
 * FlowOrientation selects a flow's axis (mirrors pptx-go's
 * scene.FlowOrientation).
 */
export type FlowOrientation = string;
/**
 * Flow orientations (wire values per compose-a-scene).
 */
export const FlowHorizontal: FlowOrientation = "horizontal";
/**
 * Flow orientations (wire values per compose-a-scene).
 */
export const FlowVertical: FlowOrientation = "vertical";
/**
 * ConnectorKind selects the connector style between flow steps (mirrors
 * pptx-go's scene.ConnectorKind; ConnectorArrow is the default).
 */
export type ConnectorKind = string;
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorArrow: ConnectorKind = "arrow";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorArrowDashed: ConnectorKind = "arrow_dashed";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorCycle: ConnectorKind = "cycle";
/**
 * Connector styles (wire values per compose-a-scene).
 */
export const ConnectorPlus: ConnectorKind = "plus";
/**
 * FlowStep is one step in a Flow. Mirror of scene.FlowStep. Icon is a closed-
 * name curated/extension icon (Stage-1 validated at render time).
 */
export interface FlowStep {
  /**
   * Label is the step heading.
   */
  label?: RichText;
  /**
   * Detail is the step body/description.
   */
  detail?: RichText;
  /**
   * Icon is a closed-name curated/extension icon name.
   */
  icon?: string;
}
/**
 * Flow is an ordered sequence of connected steps. Renders as native PPTX
 * shapes. Mirror of pptx-go's scene.Flow. At least one step is required
 * (validation, later unit).
 */
export interface Flow {
  /**
   * Orientation is the flow axis.
   */
  orientation?: FlowOrientation;
  /**
   * Steps is the ordered flow steps.
   */
  steps?: FlowStep[];
  /**
   * Connector is the connector style between steps.
   */
  connector?: ConnectorKind;
}
/**
 * Grid lays out children in a column grid. Columns is 2..4; Cells length is a
 * multiple of Columns; Ratio is empty or len == Columns (validation, later
 * unit). Mirror of scene.Grid. Children nest recursively.
 */
export interface Grid {
  /**
   * Columns is the cell count per row, 2..4.
   */
  columns?: number /* int */;
  /**
   * Ratio is an optional per-column width ratio; empty or len == Columns.
   */
  ratio?: number /* int */[];
  /**
   * Gap is the spacing between cells.
   */
  gap?: SpaceRole;
  /**
   * Cells is the grid children, a multiple of Columns.
   */
  cells?: SlideNode[];
}
/**
 * Hero is a cover/title slide node: an eyebrow, a title, and a subtitle.
 * Renders as native PPTX shapes. Mirror of pptx-go's scene.Hero.
 */
export interface Hero {
  /**
   * Eyebrow is the small label above the title.
   */
  eyebrow?: string;
  /**
   * Title is the headline.
   */
  title?: string;
  /**
   * Subtitle is the supporting line under the title.
   */
  subtitle?: string;
}
/**
 * Heading is a typed heading line at a 1..6 depth. Mirror of scene.Heading.
 */
export interface Heading {
  /**
   * Text is the heading content.
   */
  text?: RichText;
  /**
   * Level is the heading depth, 1..6.
   */
  level?: number /* int */;
}
/**
 * Prose is body text: an ordered list of paragraphs, each a RichText. Mirror
 * of scene.Prose.
 */
export interface Prose {
  /**
   * Paragraphs is the ordered body text, one RichText per paragraph.
   */
  paragraphs?: RichText[];
}
/**
 * ListKind selects a list style (mirrors pptx-go's scene.ListKind).
 */
export type ListKind = string;
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListBullet: ListKind = "bullet";
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListNumber: ListKind = "number";
/**
 * List styles (wire values per CONVENTIONS §2 example).
 */
export const ListChecklist: ListKind = "checklist";
/**
 * ListItem is one entry in a List. Mirror of scene.ListItem.
 */
export interface ListItem {
  /**
   * Text is the item's content.
   */
  text?: RichText;
  /**
   * Level is the nesting depth (0 = top-level).
   */
  level?: number /* int */;
  /**
   * Checked marks a checklist item as done (ListChecklist only).
   */
  checked?: boolean;
}
/**
 * List is a bullet, numbered, or checklist list. Mirror of scene.List. The
 * JSON field for the list style is "listKind" (not "kind", which is reserved
 * for the node discriminator — CONVENTIONS §2).
 */
export interface List {
  /**
   * Kind is the list style.
   */
  listKind?: ListKind;
  /**
   * Items is the ordered list entries.
   */
  items?: ListItem[];
}
/**
 * Image is a picture placed from caller-supplied bytes resolved by
 * AssetID. Renders as a PPTX picture (D-011). Mirror of pptx-go's
 * scene.Image. Stage-1 validation: non-empty AssetID and crop bounds (each
 * edge in [0,1], Left+Right < 1, Top+Bottom < 1) — later unit.
 */
export interface Image {
  /**
   * AssetID is the resolver key for the image bytes.
   */
  assetId?: AssetID;
  /**
   * Alt is the accessibility/alt-text description.
   */
  alt?: string;
  /**
   * Frame selects a device frame around the image.
   */
  frame?: FrameKind;
  /**
   * FrameName overrides Frame and selects a WithFrameExtension frame.
   */
  frameName?: string;
  /**
   * Crop is the per-edge crop fractions; the zero value is no crop.
   */
  crop?: Crop;
  /**
   * Fit selects how the image fills its slot; FitFill is the default.
   */
  fit?: Fit;
}
/**
 * CodeBlock is a source-code listing placed from a pre-rasterized image
 * resolved by AssetID (D-014). Renders as a PPTX picture. Mirror of
 * pptx-go's scene.CodeBlock. Stage-1 validation: non-empty AssetID — later
 * unit. Language and Caption are free-form and may be empty.
 */
export interface CodeBlock {
  /**
   * AssetID is the resolver key for the rendered code image.
   */
  assetId?: AssetID;
  /**
   * Language is the source language label (free-form).
   */
  language?: string;
  /**
   * Caption is the optional listing caption/filename.
   */
  caption?: string;
}
/**
 * Chart is a chart placed from a pre-rasterized image resolved by AssetID
 * (V1: image-shape; native c:chart is V2 — D-004). Renders as a PPTX
 * picture, or a labeled ChartPlaceholder when the asset is unresolved.
 * Mirror of pptx-go's scene.Chart. Stage-1 validation: non-empty AssetID —
 * later unit.
 */
export interface Chart {
  /**
   * AssetID is the resolver key for the chart image bytes.
   */
  assetId?: AssetID;
  /**
   * Caption is the optional chart caption.
   */
  caption?: string;
}
/**
 * ChipTone selects a chip's visual treatment (mirrors pptx-go's
 * scene.ChipTone).
 */
export type ChipTone = string;
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipTint: ChipTone = "tint";
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipSolid: ChipTone = "solid";
/**
 * Chip tones (wire values per compose-a-scene).
 */
export const ChipOutline: ChipTone = "outline";
/**
 * Chip is a compact label/badge. Renders as native PPTX shapes. Mirror of
 * pptx-go's scene.Chip. The JSON field for the tone is "tone" (the node
 * discriminator "kind" is reserved — CONVENTIONS §2).
 */
export interface Chip {
  /**
   * Label is the chip text.
   */
  label?: string;
  /**
   * Tone is the chip visual treatment.
   */
  tone?: ChipTone;
  /**
   * Color is the chip color role.
   */
  color?: ColorRole;
}
/**
 * ArrowDirection selects an arrow's direction (mirrors pptx-go's
 * scene.ArrowDirection).
 */
export type ArrowDirection = string;
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowRight: ArrowDirection = "right";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowLeft: ArrowDirection = "left";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowUp: ArrowDirection = "up";
/**
 * Arrow directions (wire values per compose-a-scene).
 */
export const ArrowDown: ArrowDirection = "down";
/**
 * Arrow is a directional connector with an optional label. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Arrow.
 */
export interface Arrow {
  /**
   * Direction is the arrow direction.
   */
  direction?: ArrowDirection;
  /**
   * Label is the optional arrow label.
   */
  label?: string;
}
/**
 * SectionDivider is a full-bleed section break with an eyebrow and a label.
 * Renders as native PPTX shapes. Mirror of pptx-go's scene.SectionDivider.
 */
export interface SectionDivider {
  /**
   * Eyebrow is the small label above the section label.
   */
  eyebrow?: string;
  /**
   * Label is the section heading.
   */
  label?: string;
}
/**
 * Quote is a block quotation with an optional attribution. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Quote.
 */
export interface Quote {
  /**
   * Text is the quotation content.
   */
  text?: RichText;
  /**
   * Attribution is the optional source/author line.
   */
  attribution?: string;
}
/**
 * Table is a grid of cells with a header row and a caption. Renders as native
 * PPTX shapes. Mirror of pptx-go's scene.Table. Each header cell and each
 * body cell is a RichText; every row width MUST equal the header width
 * (validation, later unit).
 */
export interface Table {
  /**
   * Headers is the header row, one RichText per column.
   */
  headers?: RichText[];
  /**
   * Rows is the body rows; each row is one RichText per column.
   */
  rows?: RichText[][];
  /**
   * Caption is the optional table caption.
   */
  caption?: string;
}
/**
 * ColumnRatio names a left:right width split (mirrors pptx-go's
 * scene.ColumnRatio; CONVENTIONS §2 uses "1:1").
 */
export type ColumnRatio = string;
/**
 * Column ratios.
 */
export const Ratio11: ColumnRatio = "1:1";
/**
 * Column ratios.
 */
export const Ratio12: ColumnRatio = "1:2";
/**
 * Column ratios.
 */
export const Ratio21: ColumnRatio = "2:1";
/**
 * TwoColumn splits a slide into left and right child columns. Both sides
 * must be non-empty (validation, later unit). Mirror of scene.TwoColumn.
 * Children are []SlideNode and nest recursively.
 */
export interface TwoColumn {
  /**
   * Ratio is the left:right width split.
   */
  ratio?: ColumnRatio;
  /**
   * Left is the left-column children.
   */
  left?: SlideNode[];
  /**
   * Right is the right-column children.
   */
  right?: SlideNode[];
}
/**
 * ColorRole names a surface fill color role (mirrors pptx-go's ColorRole;
 * the soul/theme resolves it to concrete RGB at render time).
 */
export type ColorRole = string;
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorCanvas: ColorRole = "canvas";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSurface: ColorRole = "surface";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSurfaceAlt: ColorRole = "surfaceAlt";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccent: ColorRole = "accent";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccentAlt: ColorRole = "accentAlt";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorAccentWarm: ColorRole = "accentWarm";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorSuccess: ColorRole = "success";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorWarning: ColorRole = "warning";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorError: ColorRole = "error";
/**
 * Surface color roles (mirror the define-a-theme skill enum verbatim).
 */
export const ColorInfo: ColorRole = "info";
/**
 * SpaceRole names a spacing token role (mirrors pptx-go's SpaceRole).
 */
export type SpaceRole = string;
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceXS: SpaceRole = "xs";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceSM: SpaceRole = "sm";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceMD: SpaceRole = "md";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceLG: SpaceRole = "lg";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const SpaceXL: SpaceRole = "xl";
/**
 * Spacing roles (mirror the define-a-theme skill enum verbatim).
 */
export const Space2XL: SpaceRole = "2xl";
/**
 * ElevationRole names a shadow elevation role (mirrors pptx-go's
 * ElevationRole).
 */
export type ElevationRole = string;
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationFlat: ElevationRole = "flat";
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationRaised: ElevationRole = "raised";
/**
 * Elevation roles (mirror the define-a-theme skill enum verbatim).
 */
export const ElevationElevated: ElevationRole = "elevated";
/**
 * Slide is one slide: a stable ID, a structural layout, an ordered node tree,
 * and optional speaker notes. Nodes and Notes route through the codec
 * (CONVENTIONS §2/§3): marshaling injects each node's "kind" via the node's
 * own MarshalJSON; unmarshaling dispatches each node through
 * UnmarshalSlideNode (recursion) and each run through TextRun's unmarshaler.
 */
export interface Slide {
  /**
   * ID is the slide identifier (stable, agent/human addressable).
   */
  id: string;
  /**
   * Layout is the structural intent, mapping to a master layout.
   */
  layout?: LayoutKind;
  /**
   * Nodes is the slide's top-level node tree.
   */
  nodes?: SlideNode[];
  /**
   * Notes is the speaker notes.
   */
  notes?: RichText;
}
/**
 * SlideDoc is the deck-of-slides wrapper: a title plus an ordered slide list.
 * Slides route through Slide's own marshal/unmarshal, so node trees and notes
 * are codec-handled throughout.
 */
export interface SlideDoc {
  /**
   * Title is the deck title.
   */
  title?: string;
  /**
   * Slides is the deck's slides, in order.
   */
  slides?: Slide[];
}
/**
 * RichText is an ordered list of styled runs — the inline-text content type
 * used across the slide IR (CONVENTIONS §4). It marshals as a JSON array of
 * TextRun objects; each run is a flat { text, typeRole?, bold?, ... , color? }.
 */
export type RichText = TextRun[];
/**
 * TextRun is one styled run of text. Its JSON shape is flat (CONVENTIONS §4):
 * the Style fields are inlined into the run object and Color is omitted when
 * unset (meaning the token "primary").
 */
export interface TextRun {
  /**
   * Text is the literal run content.
   */
  Text: string;
  /**
   * Style carries typography and inline formatting.
   */
  Style: RunStyle;
  /**
   * Color is the run color; the zero value means the token "primary".
   */
  Color: TextColor;
}
/**
 * RunStyle mirrors pptx-go's scene.RunStyle: typography role plus inline
 * formatting flags and a link target.
 */
export interface RunStyle {
  /**
   * TypeRole selects a typography scale role (TypeBody, TypeH2, ...).
   */
  TypeRole: TypeRole;
  /**
   * Bold toggles bold weight.
   */
  Bold: boolean;
  /**
   * Italic toggles italic style.
   */
  Italic: boolean;
  /**
   * Underline toggles underline.
   */
  Underline: boolean;
  /**
   * Strike toggles strikethrough.
   */
  Strike: boolean;
  /**
   * Code marks the run as inline code (mono + tint).
   */
  Code: boolean;
  /**
   * Link marks the run as a hyperlink; Href is the target.
   */
  Link: boolean;
  /**
   * Href is the link URL when Link is true.
   */
  Href: string;
}
/**
 * TextColor is a run color: either a soul-bound token role (the documented
 * default) or a literal RGB escape hatch. The zero value is the token
 * "primary". JSON: { "token": "<role>" } or { "literal": "RRGGBB" }.
 */
export interface TextColor {
  /**
   * Token is a semantic text-color role resolved against the soul/theme.
   */
  token?: TextColorRole;
  /**
   * Literal is an explicit "RRGGBB" hex color bypassing the theme.
   */
  literal?: string;
}
/**
 * TextColorRole names a semantic text-color role (mirrors pptx-go's
 * TextColorRole; CONVENTIONS §4 lists the wire values verbatim).
 */
export type TextColorRole = string;
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextPrimary: TextColorRole = "primary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextSecondary: TextColorRole = "secondary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextTertiary: TextColorRole = "tertiary";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextInverse: TextColorRole = "inverse";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextMuted: TextColorRole = "muted";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextAccent: TextColorRole = "accent";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextAccentAlt: TextColorRole = "accentAlt";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextSuccess: TextColorRole = "success";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextWarning: TextColorRole = "warning";
/**
 * Text color roles (wire values per CONVENTIONS §4).
 */
export const TextError: TextColorRole = "error";
/**
 * TypeRole names a typography scale role (mirrors pptx-go's TypeRole; wire
 * values per CONVENTIONS §4: body|h1|h2|h3|code|...).
 */
export type TypeRole = string;
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeDisplay: TypeRole = "display";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH1: TypeRole = "h1";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH2: TypeRole = "h2";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH3: TypeRole = "h3";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH4: TypeRole = "h4";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeH5: TypeRole = "h5";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeBody: TypeRole = "body";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeBodySmall: TypeRole = "bodySmall";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeCaption: TypeRole = "caption";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeMono: TypeRole = "mono";
/**
 * Typography roles (mirror the define-a-theme skill enum verbatim).
 */
export const TypeCode: TypeRole = "code";
/**
 * SlideValidation is the structural validation result for one slide.
 */
export interface SlideValidation {
  /**
   * OK reports whether ValidateSlide returned no issues.
   */
  ok: boolean;
  /**
   * Issues is the flattened list of validation issue messages.
   */
  issues?: string[];
}
/**
 * AddSlideInput is the typed input for add_slide.
 */
export interface AddSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Slide is the slide snapshot to insert. Its ID is ignored on add.
   */
  slide: Slide;
  /**
   * Position is the optional zero-based insertion index.
   */
  position?: number /* int */;
}
/**
 * AddSlideOutput is the structured result for add_slide.
 */
export interface AddSlideOutput {
  /**
   * SlideID is the inserted slide identifier assigned by the store.
   */
  slideId: string;
  /**
   * Slide is the stored slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * UpdateSlideInput is the typed input for update_slide.
 */
export interface UpdateSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to replace.
   */
  slideId: string;
  /**
   * Slide is the replacement slide snapshot.
   */
  slide: Slide;
  /**
   * ExpectedRevisionHash enforces optimistic concurrency when set.
   */
  expectedRevisionHash?: string;
}
/**
 * UpdateSlideOutput is the structured result for update_slide.
 */
export interface UpdateSlideOutput {
  /**
   * SlideID is the updated slide identifier.
   */
  slideId: string;
  /**
   * Slide is the stored replacement slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the stored slide.
   */
  validation: SlideValidation;
}
/**
 * GetSlideInput is the typed input for get_slide.
 */
export interface GetSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to load.
   */
  slideId: string;
}
/**
 * GetSlideOutput is the structured result for get_slide.
 */
export interface GetSlideOutput {
  /**
   * SlideID is the loaded slide identifier.
   */
  slideId: string;
  /**
   * Slide is the loaded slide snapshot.
   */
  slide: Slide;
  /**
   * Validation is the structural validation result for the loaded slide.
   */
  validation: SlideValidation;
}
/**
 * RemoveSlideInput is the typed input for remove_slide.
 */
export interface RemoveSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to delete.
   */
  slideId: string;
}
/**
 * RemoveSlideOutput is the structured result for remove_slide.
 */
export interface RemoveSlideOutput {
  /**
   * DeckID is the updated deck identifier.
   */
  deckId: string;
  /**
   * Removed reports whether the slide was removed.
   */
  removed: boolean;
}
/**
 * ReorderSlidesInput is the typed input for reorder_slides.
 */
export interface ReorderSlidesInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * Order is the complete ordered list of slide IDs.
   */
  order?: string[];
}
/**
 * ReorderSlidesOutput is the structured result for reorder_slides.
 */
export interface ReorderSlidesOutput {
  /**
   * Kind identifies this payload as a deck result.
   */
  kind: DeckKind;
  /**
   * DeckID is the reordered deck identifier.
   */
  deckId: string;
  /**
   * Slides is the ordered preview summary after reordering.
   */
  slides?: SlideSummary[];
}
/**
 * DuplicateSlideInput is the typed input for duplicate_slide.
 */
export interface DuplicateSlideInput {
  /**
   * DeckID addresses the deck by stable ID or slug.
   */
  deckId: string;
  /**
   * SlideID is the stable slide identifier to copy.
   */
  slideId: string;
  /**
   * Position is the optional zero-based insertion index for the copy.
   */
  position?: number /* int */;
}
/**
 * DuplicateSlideOutput is the structured result for duplicate_slide.
 */
export interface DuplicateSlideOutput {
  /**
   * SlideID is the inserted duplicate slide identifier.
   */
  slideId: string;
  /**
   * Slide is the stored duplicate slide snapshot.
   */
  slide: Slide;
}
